#!/usr/bin/env bash
set -Eeuo pipefail

usage() { echo "Usage: $0 --inventory FILE --node-name SSH_ALIAS --account-public FILE [--consensus-pubkey BASE64] [--join-profile FILE] [--seeds-file FILE|--bootstrap] --secrets-dir DIR [--state-sync-env FILE --data-dir DIR] [--poc-callback-url URL --ml-callback-bind IP] --output FILE" >&2; }
INVENTORY=''; NODE=''; ACCOUNT=''; CONSENSUS_PUBKEY=''; SEEDS_FILE=''; SECRETS=''; OUTPUT=''; STATE_SYNC_ENV=''; DATA_DIR_OVERRIDE=''; JOIN_PROFILE=''; BOOTSTRAP=false; POC_CALLBACK_URL='http://api:9100'; ML_CALLBACK_BIND='127.0.0.1'
while (($#)); do case "$1" in
  --inventory) INVENTORY="$2"; shift 2 ;;
  --node-name) NODE="$2"; shift 2 ;;
  --account-public) ACCOUNT="$2"; shift 2 ;;
  --consensus-pubkey) CONSENSUS_PUBKEY="$2"; shift 2 ;;
  --seeds-file) SEEDS_FILE="$2"; shift 2 ;;
  --bootstrap) BOOTSTRAP=true; shift ;;
  --secrets-dir) SECRETS="$2"; shift 2 ;;
  --state-sync-env) STATE_SYNC_ENV="$2"; shift 2 ;;
  --join-profile) JOIN_PROFILE="$2"; shift 2 ;;
  --data-dir) DATA_DIR_OVERRIDE="$2"; shift 2 ;;
  --poc-callback-url) POC_CALLBACK_URL="$2"; shift 2 ;;
  --ml-callback-bind) ML_CALLBACK_BIND="$2"; shift 2 ;;
  --output) OUTPUT="$2"; shift 2 ;;
  *) usage; exit 2 ;;
esac; done
[[ "$NODE" =~ ^[a-z0-9][a-z0-9_-]*$ ]] || { usage; exit 2; }
[[ -z "$DATA_DIR_OVERRIDE" || "$DATA_DIR_OVERRIDE" =~ ^/srv/dai/data/${NODE}\.generations/[A-Za-z0-9._-]+$ ]] \
  || { echo 'state-sync data directory must be the named Host generation under /srv/dai/data' >&2; exit 2; }
[[ "$POC_CALLBACK_URL" =~ ^http://([0-9]{1,3}\.){3}[0-9]{1,3}:9100$|^http://api:9100$ ]] || { echo 'PoC callback URL must be http://api:9100 or an IPv4 address on port 9100' >&2; exit 2; }
[[ "$ML_CALLBACK_BIND" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || { echo 'ML callback bind must be an IPv4 address' >&2; exit 2; }
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT/scripts/lib.sh"
load_env "$INVENTORY"
load_topology
source "$ROOT/scripts/profile.sh"
if [[ -n "$JOIN_PROFILE" ]]; then
  load_join_profile "$JOIN_PROFILE"
  [[ "$CHAIN_ID" == "$(jq -r .spec.network.chain_id "$JOIN_PROFILE")" ]] || { echo 'generated JOIN profile and inventory chain IDs differ' >&2; exit 1; }
else
  load_profiles
fi
topology_contains_node "$NODE" || { echo "node is not configured in inventory: $NODE" >&2; exit 2; }
PUBLIC_HOST="$(node_public_host "$NODE")"
P2P_PORT="$(node_p2p_port "$NODE")"
ADDRESS="$(jq -r .address "$ACCOUNT")"
PUBKEY="$(jq -r .account_pubkey_b64 "$ACCOUNT")"
[[ "$ADDRESS" =~ ^gonka1[0-9a-z]{20,90}$ ]] || { echo "Invalid account: $ACCOUNT" >&2; exit 1; }
if [[ -n "$CONSENSUS_PUBKEY" ]]; then
  [[ "$(base64 -d <<<"$CONSENSUS_PUBKEY" 2>/dev/null | wc -c | tr -d ' ')" == 32 ]] \
    || { echo 'consensus public key must be a base64 Ed25519 key' >&2; exit 1; }
fi
if [[ "$BOOTSTRAP" == true ]]; then
  SEEDS='identity-bootstrap-only'
else
  # Compose env files accept one physical line per assignment, while the
  # validated Bootstrap stage intentionally records one seed per line for
  # inspection.  CometBFT consumes the same entries as a comma-delimited
  # list, so serialize them before writing the node environment.
  SEEDS="$(paste -sd, "$SEEDS_FILE")"
  [[ -n "$SEEDS" ]] || { echo "seed file is empty: $SEEDS_FILE" >&2; exit 1; }
fi
if [[ -n "$STATE_SYNC_ENV" ]]; then
  source_rpc=''
  operator_source_rpc=''
  [[ -z "$JOIN_PROFILE" ]] || operator_source_rpc="$(jq -r '.spec.state_acquisition.trust_authority | select(.kind == "operator_source") | .rpc_url' "$JOIN_PROFILE")"
  [[ -r "$STATE_SYNC_ENV" ]] || { echo "state-sync environment is unreadable: $STATE_SYNC_ENV" >&2; exit 2; }
  # Generated by the bounded lineage preflight, never operator supplied.
  # shellcheck disable=SC1090
  source "$STATE_SYNC_ENV"
  [[ "${GDC_JOIN_BOOTSTRAP_MODE:-}" == state_sync && "${GDC_JOIN_TRUST_HEIGHT:-}" =~ ^[1-9][0-9]*$ && "${GDC_JOIN_TRUST_HASH:-}" =~ ^[0-9a-f]{64}$ ]] \
    || { echo 'state-sync environment is incomplete' >&2; exit 1; }
  if [[ -n "$operator_source_rpc" ]]; then
    [[ "${GDC_JOIN_SOURCE_RPC:-}" == "$operator_source_rpc" ]] || { echo 'source authority differs from Join Profile' >&2; exit 1; }
  fi
  source_rpc="${GDC_JOIN_SOURCE_RPC:-$operator_source_rpc}"
  if [[ -n "$source_rpc" ]]; then
    [[ "${GDC_JOIN_RPC_SERVER_1:-}" == "$source_rpc/" && "${GDC_JOIN_RPC_SERVER_2:-}" != "$source_rpc/" && "$GDC_JOIN_SNAPSHOT_PEERS" == *,* ]] \
      || { echo 'state sync requires the selected archival source plus an independent witness' >&2; exit 1; }
  fi
  [[ "${GDC_JOIN_RPC_SERVER_1:-}" =~ ^https?://[A-Za-z0-9.-]+(:[1-9][0-9]{0,4})?/chain-rpc/$ ]] || { echo 'JOIN environment lacks its source RPC' >&2; exit 1; }
  [[ "${GDC_JOIN_RPC_SERVER_2:-}" =~ ^https?://[A-Za-z0-9.-]+(:[1-9][0-9]{0,4})?/chain-rpc/$ && "$GDC_JOIN_RPC_SERVER_1" != "$GDC_JOIN_RPC_SERVER_2" ]] || { echo 'state-sync environment lacks independent RPC URLs' >&2; exit 1; }
  [[ "${GDC_JOIN_SNAPSHOT_PEERS:-}" == *,* ]] || { echo 'state-sync environment lacks two P2P snapshot providers' >&2; exit 1; }
  [[ "${GDC_JOIN_SNAPSHOT_PEERS:-}" =~ ^[0-9a-f]{40}@tcp://[A-Za-z0-9.-]+:[0-9]{2,5}(,[0-9a-f]{40}@tcp://[A-Za-z0-9.-]+:[0-9]{2,5})*$ ]] || { echo 'JOIN environment lacks valid P2P providers' >&2; exit 1; }
fi
snapshot_peers="${GDC_JOIN_SNAPSHOT_PEERS:-}"
# Bootstrap evidence uses its public `tcp://` endpoint form. CometBFT 0.38's
# `persistent_peers` parser accepts the same endpoints only as ID@host:port.
# Keep the observed form in the receipt and derive the runtime-only form here.
persistent_peers="$(sed 's/@tcp:\/\//@/g' <<<"$snapshot_peers")"
[[ -z "$snapshot_peers" || "$persistent_peers" =~ ^[0-9a-f]{40}@[A-Za-z0-9.-]+:[0-9]{2,5}(,[0-9a-f]{40}@[A-Za-z0-9.-]+:[0-9]{2,5})*$ ]] \
  || { echo 'state-sync P2P provider cannot be converted into CometBFT persistent_peers syntax' >&2; exit 1; }
KEYRING_PASSWORD="$(<"$SECRETS/$NODE.keyring")"
join_pex=true
[[ -z "$JOIN_PROFILE" ]] || join_pex="$(jq -r 'if .spec.state_acquisition | has("pex") then .spec.state_acquisition.pex else true end' "$JOIN_PROFILE")"
join_seeds="$SEEDS"
[[ "$join_pex" == false || -n "${operator_source_rpc:-}" ]] && join_seeds=''
POSTGRES_PASSWORD="$(<"$SECRETS/$NODE.postgres")"
IS_GENESIS=false; [[ "$NODE" == "$GENESIS_NODE" ]] && IS_GENESIS=true
# The public edge reaches the gateway's node proxy on port 8000. A recovered
# gateway can be a non-Genesis Host, so tying this bind only to IS_GENESIS
# strands the public API behind an unreachable loopback listener. No other
# Host needs an externally reachable proxy port.
proxy_bind_address=127.0.0.1
if [[ "$IS_GENESIS" == true || "$NODE" == "${GATEWAY_NODE:-}" ]]; then
  proxy_bind_address=0.0.0.0
fi
profile_vars=("GDC_PROFILE_KIND=generated_join" "GDC_JOIN_PROFILE_SHA256=${GDC_JOIN_PROFILE_SHA256:-}")
if [[ -z "$JOIN_PROFILE" ]]; then
  profile_vars=("GDC_PROFILE_KIND=release" "GDC_RELEASE_PROFILE=$GDC_RELEASE_PROFILE" "GDC_PROFILE_HASH=$(profile_hash)")
fi
write_env "$OUTPUT" \
  "COMPOSE_PROJECT_NAME=$NODE" "COMPOSE_PROFILES=$EDGE_API_COMPOSE_PROFILE" "NODE_NAME=$NODE" "CHAIN_ID=$CHAIN_ID" "BASE_DENOM=$BASE_DENOM" \
  "${profile_vars[@]}" "GONKA_COMMIT=$GONKA_COMMIT" \
  "PUBLIC_HOST=$PUBLIC_HOST" "PUBLIC_URL=https://$PUBLIC_HOST" "P2P_PORT=$P2P_PORT" \
  "GDC_STOP_POC_AT_WINDDOWN=${GDC_STOP_POC_AT_WINDDOWN:-true}" \
  "P2P_EXTERNAL_ADDRESS=tcp://$PUBLIC_HOST:$P2P_PORT" "LOCAL_PROXY_PORT=8000" \
  "DATA_DIR=${DATA_DIR_OVERRIDE:-${DATA_ROOT%/}/$NODE}" "IDENTITY_DIR=/srv/dai/identity/$NODE" "SIGNER_DIR=/srv/dai/signer/$NODE" "HF_HOME=$HF_CACHE_ROOT" "GENESIS_FILE=$GENESIS_INSTALL_PATH" \
  "PROXY_BIND_ADDRESS=$proxy_bind_address" \
  "NODE_CONFIG_FILE=./node-config.json" "ACCOUNT_ADDRESS=$ADDRESS" "ACCOUNT_PUBKEY=$PUBKEY" "CONSENSUS_PUBKEY=$CONSENSUS_PUBKEY" \
  "KEY_NAME=$NODE-warm" "KEYRING_PASSWORD=$KEYRING_PASSWORD" "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" \
  "DAPI_API__POC_CALLBACK_URL=$POC_CALLBACK_URL" "ML_CALLBACK_BIND=$ML_CALLBACK_BIND" \
  "IS_GENESIS=$IS_GENESIS" "INIT_ONLY=false" "GENESIS_SEEDS=$SEEDS" "SYNC_WITH_SNAPSHOTS=true" \
  "GDC_JOIN_STATESYNC_ENABLE=true" \
  "GDC_JOIN_RPC_SERVERS=${GDC_JOIN_RPC_SERVER_1:-},${GDC_JOIN_RPC_SERVER_2:-}" \
  "GDC_JOIN_TRUST_HEIGHT=${GDC_JOIN_TRUST_HEIGHT:-0}" "GDC_JOIN_TRUST_HASH=${GDC_JOIN_TRUST_HASH:-}" \
  "GDC_JOIN_SNAPSHOT_PEERS=$snapshot_peers" "GDC_JOIN_PERSISTENT_PEERS=$persistent_peers" \
  "GDC_JOIN_PEX=$join_pex" "GDC_JOIN_SEEDS=$join_seeds" \
  "TRUSTED_BLOCK_PERIOD=${GDC_JOIN_TRUSTED_BLOCK_PERIOD:-2000}" \
  "SEED_API_URL=https://$GENESIS_PUBLIC_HOST" "SEED_NODE_RPC_URL=${GDC_JOIN_RPC_SERVER_1:-https://$GENESIS_PUBLIC_HOST/chain-rpc/}" \
  "SEED_NODE_P2P_URL=tcp://$GENESIS_PUBLIC_HOST:$GENESIS_P2P_PORT" \
  "RPC_SERVER_URL_1=${GDC_JOIN_RPC_SERVER_1:-https://$GENESIS_PUBLIC_HOST/chain-rpc/}" "RPC_SERVER_URL_2=${GDC_JOIN_RPC_SERVER_2:-https://$PUBLIC_EDGE_HOST/chain-rpc/}" \
  "TMKMS_IMAGE=$TMKMS_IMAGE" "INFERENCED_IMAGE=$INFERENCED_IMAGE" "POSTGRES_IMAGE=$POSTGRES_IMAGE" \
  "DAPI_IMAGE=$DAPI_IMAGE" "DAPI_UPGRADE_URL=${DAPI_UPGRADE_URL:-}" "DAPI_UPGRADE_SHA256=${DAPI_UPGRADE_SHA256:-}" "DAPI_EXPECTED_VERSION=${DAPI_EXPECTED_VERSION:-}" "DAPI_EXPECTED_COMMIT=${DAPI_EXPECTED_COMMIT:-}" "EDGE_API_IMAGE=$EDGE_API_IMAGE" "EDGE_API_SERVICE_NAME=$EDGE_API_SERVICE_NAME" "VERSIOND_IMAGE=$VERSIOND_IMAGE" "PROXY_IMAGE=$PROXY_IMAGE" \
  "EXPLORER_IMAGE=$EXPLORER_IMAGE" "DASHBOARD_PORT=$DASHBOARD_PORT" \
  "MLNODE_IMAGE=$MLNODE_GENERIC_IMAGE" "MLNODE_PROXY_IMAGE=$MLNODE_PROXY_IMAGE" \
  "ACCELERATOR_VENDOR=${ACCELERATOR_VENDOR:-nvidia}" "ACCELERATOR_QUALIFICATION_BACKEND=${ACCELERATOR_QUALIFICATION_BACKEND:-cuda}" \
  "MLNODE_COMPOSE_VARIANT=${MLNODE_COMPOSE_VARIANT:-nvidia}" \
  "AMD_KFD_DEVICE=${AMD_KFD_DEVICE:-}" "AMD_RENDER_DEVICE=${AMD_RENDER_DEVICE:-}" \
  "AMD_KFD_GROUP_ID=${AMD_KFD_GROUP_ID:-}" "AMD_RENDER_GROUP_ID=${AMD_RENDER_GROUP_ID:-}" \
  "POC_BATCH_SIZE_DEFAULT=32"
echo "$OUTPUT"
