#!/usr/bin/env bash
set -Eeuo pipefail

usage() { echo "Usage: $0 --inventory FILE --node-name SSH_ALIAS --account-public FILE [--seeds-file FILE|--bootstrap] --secrets-dir DIR [--state-sync-env FILE --data-dir DIR] [--poc-callback-url URL --ml-callback-bind IP] --output FILE" >&2; }
INVENTORY=''; NODE=''; ACCOUNT=''; SEEDS_FILE=''; SECRETS=''; OUTPUT=''; STATE_SYNC_ENV=''; DATA_DIR_OVERRIDE=''; BOOTSTRAP=false; POC_CALLBACK_URL='http://api:9100'; ML_CALLBACK_BIND='127.0.0.1'
while (($#)); do case "$1" in
  --inventory) INVENTORY="$2"; shift 2 ;;
  --node-name) NODE="$2"; shift 2 ;;
  --account-public) ACCOUNT="$2"; shift 2 ;;
  --seeds-file) SEEDS_FILE="$2"; shift 2 ;;
  --bootstrap) BOOTSTRAP=true; shift ;;
  --secrets-dir) SECRETS="$2"; shift 2 ;;
  --state-sync-env) STATE_SYNC_ENV="$2"; shift 2 ;;
  --data-dir) DATA_DIR_OVERRIDE="$2"; shift 2 ;;
  --poc-callback-url) POC_CALLBACK_URL="$2"; shift 2 ;;
  --ml-callback-bind) ML_CALLBACK_BIND="$2"; shift 2 ;;
  --output) OUTPUT="$2"; shift 2 ;;
  *) usage; exit 2 ;;
esac; done
[[ "$NODE" =~ ^[a-z0-9][a-z0-9_-]*$ ]] || { usage; exit 2; }
[[ -z "$DATA_DIR_OVERRIDE" || "$DATA_DIR_OVERRIDE" =~ ^/srv/dai/data/[a-z0-9][a-z0-9_.-]*$ ]] || { echo 'state-sync data directory must be under /srv/dai/data' >&2; exit 2; }
[[ "$POC_CALLBACK_URL" =~ ^http://([0-9]{1,3}\.){3}[0-9]{1,3}:9100$|^http://api:9100$ ]] || { echo 'PoC callback URL must be http://api:9100 or an IPv4 address on port 9100' >&2; exit 2; }
[[ "$ML_CALLBACK_BIND" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || { echo 'ML callback bind must be an IPv4 address' >&2; exit 2; }
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT/scripts/lib.sh"
load_env "$INVENTORY"
load_topology
source "$ROOT/scripts/profile.sh"
load_profiles
topology_contains_node "$NODE" || { echo "node is not configured in inventory: $NODE" >&2; exit 2; }
PUBLIC_HOST="$(node_public_host "$NODE")"
P2P_PORT="$(node_p2p_port "$NODE")"
ADDRESS="$(jq -r .address "$ACCOUNT")"
PUBKEY="$(jq -r .account_pubkey_b64 "$ACCOUNT")"
[[ "$ADDRESS" =~ ^gonka1[0-9a-z]{20,90}$ ]] || { echo "Invalid account: $ACCOUNT" >&2; exit 1; }
if [[ "$BOOTSTRAP" == true ]]; then
  SEEDS='identity-bootstrap-only'
else
  # Compose env files accept one physical line per assignment, while the
  # validated Bootstrap stage intentionally records one seed per line for
  # inspection.  CometBFT consumes the same entries as a comma-delimited
  # list, so serialize them before writing the node environment.
  SEEDS="$(paste -sd, "$SEEDS_FILE")"
  [[ -n "$SEEDS" ]] || { echo "seed file is empty: $SEEDS_FILE" >&2; exit 1; }
fi
if [[ -n "$STATE_SYNC_ENV" ]]; then
  [[ -r "$STATE_SYNC_ENV" ]] || { echo "state-sync environment is unreadable: $STATE_SYNC_ENV" >&2; exit 2; }
  # Generated by the bounded lineage preflight, never operator supplied.
  # shellcheck disable=SC1090
  source "$STATE_SYNC_ENV"
  [[ "${GDC_JOIN_BOOTSTRAP_MODE:-}" == state_sync && "${GDC_JOIN_TRUST_HEIGHT:-}" =~ ^[1-9][0-9]*$ && "${GDC_JOIN_TRUST_HASH:-}" =~ ^[0-9a-f]{64}$ ]] \
    || { echo 'state-sync environment is incomplete' >&2; exit 1; }
  [[ "${GDC_JOIN_RPC_SERVER_1:-}" =~ ^https://[A-Za-z0-9.-]+/chain-rpc/$ && "${GDC_JOIN_RPC_SERVER_2:-}" =~ ^https://[A-Za-z0-9.-]+/chain-rpc/$ && "$GDC_JOIN_RPC_SERVER_1" != "$GDC_JOIN_RPC_SERVER_2" ]] \
    || { echo 'state-sync environment lacks independent RPC URLs' >&2; exit 1; }
  [[ "${GDC_JOIN_SNAPSHOT_PEERS:-}" =~ ^[0-9a-f]{40}@tcp://[A-Za-z0-9.-]+:[0-9]{2,5}(,[0-9a-f]{40}@tcp://[A-Za-z0-9.-]+:[0-9]{2,5})+$ ]] \
    || { echo 'state-sync environment lacks two P2P snapshot providers' >&2; exit 1; }
fi
KEYRING_PASSWORD="$(<"$SECRETS/$NODE.keyring")"
POSTGRES_PASSWORD="$(<"$SECRETS/$NODE.postgres")"
IS_GENESIS=false; [[ "$NODE" == "$GENESIS_NODE" ]] && IS_GENESIS=true
write_env "$OUTPUT" \
  "COMPOSE_PROJECT_NAME=$NODE" "COMPOSE_PROFILES=$EDGE_API_COMPOSE_PROFILE" "NODE_NAME=$NODE" "CHAIN_ID=$CHAIN_ID" "BASE_DENOM=$BASE_DENOM" \
  "GDC_RELEASE_PROFILE=$GDC_RELEASE_PROFILE" "GDC_PROFILE_HASH=$(profile_hash)" "GONKA_COMMIT=$GONKA_COMMIT" \
  "PUBLIC_HOST=$PUBLIC_HOST" "PUBLIC_URL=https://$PUBLIC_HOST" "P2P_PORT=$P2P_PORT" \
  "GDC_STOP_POC_AT_WINDDOWN=${GDC_STOP_POC_AT_WINDDOWN:-true}" \
  "P2P_EXTERNAL_ADDRESS=tcp://$PUBLIC_HOST:$P2P_PORT" "LOCAL_PROXY_PORT=8000" \
  "DATA_DIR=${DATA_DIR_OVERRIDE:-${DATA_ROOT%/}/$NODE}" "HF_HOME=$HF_CACHE_ROOT" "GENESIS_FILE=$GENESIS_INSTALL_PATH" \
  "PROXY_BIND_ADDRESS=$([[ "$IS_GENESIS" == true ]] && echo 0.0.0.0 || echo 127.0.0.1)" \
  "NODE_CONFIG_FILE=./node-config.json" "ACCOUNT_ADDRESS=$ADDRESS" "ACCOUNT_PUBKEY=$PUBKEY" \
  "KEY_NAME=$NODE-warm" "KEYRING_PASSWORD=$KEYRING_PASSWORD" "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" \
  "DAPI_API__POC_CALLBACK_URL=$POC_CALLBACK_URL" "ML_CALLBACK_BIND=$ML_CALLBACK_BIND" \
  "IS_GENESIS=$IS_GENESIS" "INIT_ONLY=false" "GENESIS_SEEDS=$SEEDS" "SYNC_WITH_SNAPSHOTS=$([[ -n "$STATE_SYNC_ENV" ]] && echo true || echo false)" \
  "GDC_JOIN_STATESYNC_ENABLE=$([[ -n "$STATE_SYNC_ENV" ]] && echo true || echo false)" \
  "GDC_JOIN_RPC_SERVERS=${GDC_JOIN_RPC_SERVER_1:-},${GDC_JOIN_RPC_SERVER_2:-}" \
  "GDC_JOIN_TRUST_HEIGHT=${GDC_JOIN_TRUST_HEIGHT:-0}" "GDC_JOIN_TRUST_HASH=${GDC_JOIN_TRUST_HASH:-}" \
  "GDC_JOIN_SNAPSHOT_PEERS=${GDC_JOIN_SNAPSHOT_PEERS:-}" \
  "TRUSTED_BLOCK_PERIOD=${GDC_JOIN_TRUSTED_BLOCK_PERIOD:-2000}" \
  "SEED_API_URL=https://$GENESIS_PUBLIC_HOST" "SEED_NODE_RPC_URL=${GDC_JOIN_RPC_SERVER_1:-https://$GENESIS_PUBLIC_HOST/chain-rpc/}" \
  "SEED_NODE_P2P_URL=tcp://$GENESIS_PUBLIC_HOST:$GENESIS_P2P_PORT" \
  "RPC_SERVER_URL_1=${GDC_JOIN_RPC_SERVER_1:-https://$GENESIS_PUBLIC_HOST/chain-rpc/}" "RPC_SERVER_URL_2=${GDC_JOIN_RPC_SERVER_2:-https://$PUBLIC_EDGE_HOST/chain-rpc/}" \
  "TMKMS_IMAGE=$TMKMS_IMAGE" "INFERENCED_IMAGE=$INFERENCED_IMAGE" "POSTGRES_IMAGE=$POSTGRES_IMAGE" \
  "DAPI_IMAGE=$DAPI_IMAGE" "EDGE_API_IMAGE=$EDGE_API_IMAGE" "EDGE_API_SERVICE_NAME=$EDGE_API_SERVICE_NAME" "VERSIOND_IMAGE=$VERSIOND_IMAGE" "PROXY_IMAGE=$PROXY_IMAGE" \
  "EXPLORER_IMAGE=$EXPLORER_IMAGE" "DASHBOARD_PORT=$DASHBOARD_PORT" \
  "MLNODE_IMAGE=$MLNODE_GENERIC_IMAGE" "MLNODE_PROXY_IMAGE=$MLNODE_PROXY_IMAGE" \
  "POC_BATCH_SIZE_DEFAULT=32"
echo "$OUTPUT"
