#!/usr/bin/env bash
# Resolve the cold-JOIN state-acquisition decision before software download or
# any Host operation. Bootstrap v1 deliberately contains no mutable trust or
# snapshot data, so this receipt records only observations made for this run.
set -Eeuo pipefail

usage() { echo "Usage: $0 --bootstrap-file FILE --composition-env FILE --receipt FILE --env FILE" >&2; }
die() {
  if [[ -n "${GDC_JOIN_LINEAGE_FAILURE_FILE:-}" ]]; then
    umask 077
    printf '%s\n' "$1" >"$GDC_JOIN_LINEAGE_FAILURE_FILE"
  fi
  printf 'lineage_%s: %s\n' "$1" "$2" >&2; exit 1
}
BOOTSTRAP=''; COMPOSITION=''; RECEIPT=''; ENV_FILE=''
while (($#)); do case "$1" in
  --bootstrap-file) BOOTSTRAP="${2:-}"; shift 2 ;;
  --composition-env) COMPOSITION="${2:-}"; shift 2 ;;
  --receipt) RECEIPT="${2:-}"; shift 2 ;;
  --env) ENV_FILE="${2:-}"; shift 2 ;;
  *) usage; exit 2 ;;
esac; done
[[ -r "$BOOTSTRAP" && -r "$COMPOSITION" && -n "$RECEIPT" && -n "$ENV_FILE" ]] || { usage; exit 2; }
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
command -v curl >/dev/null || die dependency 'curl is required'
command -v jq >/dev/null || die dependency 'jq is required'
"$ROOT/scripts/network-bootstrap.sh" verify "$BOOTSTRAP" >/dev/null
# Generated by the observer only after its immutable profile mapping checks.
# shellcheck disable=SC1090
source "$COMPOSITION"
[[ "${GDC_NETWORK_FINGERPRINT:-}" =~ ^[0-9a-f]{64}$ ]] || die configuration 'missing network fingerprint'
[[ "${GDC_NETWORK_CHAIN_ID:-}" == "$(jq -r .chain_id "$BOOTSTRAP")" ]] || die configuration 'composition and Bootstrap chain IDs differ'
[[ "${GDC_NETWORK_GENESIS_SHA256:-}" == "$(jq -r .genesis.sha256 "$BOOTSTRAP")" ]] || die configuration 'composition and Bootstrap Genesis digests differ'
source "$ROOT/scripts/profile.sh"
load_profiles

period="${GDC_JOIN_TRUSTED_BLOCK_PERIOD:-2000}"
early_height="${GDC_JOIN_EARLY_CHECKPOINT_HEIGHT:-5}"
ttl="${GDC_JOIN_PREFLIGHT_TTL_SECONDS:-600}"
[[ "$period" =~ ^[1-9][0-9]*$ && "$early_height" =~ ^[1-9][0-9]*$ && "$ttl" =~ ^[1-9][0-9]*$ ]] || die configuration 'trust period, early checkpoint and receipt TTL must be positive'
tmp="$(mktemp -d)"; trap 'rm -rf -- "$tmp"' EXIT

# Tests can supply a closed host=id map. Production always resolves a host to
# its IPv4 address. The map avoids treating two test aliases as independent.
fault_domain() {
  local host="$1" entry
  if [[ -n "${GDC_JOIN_FAULT_DOMAIN_MAP:-}" ]]; then
    IFS=, read -r -a entries <<<"$GDC_JOIN_FAULT_DOMAIN_MAP"
    for entry in "${entries[@]}"; do [[ "$entry" == "$host="* ]] && { printf '%s' "${entry#*=}"; return; }; done
    return 1
  fi
  getent ahostsv4 "$host" 2>/dev/null | awk 'NR == 1 {print $1}'
}

record_from_block() {
  jq -cer '{height:(.result.block.header.height|tonumber),block_id:(.result.block_id.hash|ascii_downcase),app_hash:(.result.block.header.app_hash|ascii_downcase)}'
}
one_record() {
  local label="$1"; shift
  local -a unique=()
  mapfile -t unique < <(printf '%s\n' "$@" | LC_ALL=C sort -u)
  (( ${#unique[@]} == 1 )) || die rpc_quorum_conflict "independent RPCs disagree at $label"
  printf '%s' "${unique[0]}"
}
api_for_rpc() { local rpc="$1"; printf '%s' "${rpc%/chain-rpc}"; }

mapfile -t rpcs < <(jq -r '.seeds[].rpc' "$BOOTSTRAP")
(( ${#rpcs[@]} >= 2 )) || die rpc_quorum_conflict 'Bootstrap has fewer than two RPC seeds'
declare -a good_rpcs=() domains=() heights=()
for rpc in "${rpcs[@]}"; do
  host="${rpc#https://}"; host="${host%%/*}"
  domain="$(fault_domain "$host" || true)"
  [[ "$domain" =~ ^[A-Za-z0-9._:-]+$ ]] || die rpc_quorum_conflict "cannot establish fault domain for $host"
  status="$tmp/status-${#good_rpcs[@]}.json"
  curl -fsS --connect-timeout 5 --max-time 15 "${rpc%/}/status" >"$status" 2>/dev/null || continue
  jq -e --arg chain "$GDC_NETWORK_CHAIN_ID" '.result.node_info.network == $chain and (.result.sync_info.latest_block_height|tonumber) > 0' "$status" >/dev/null || continue
  good_rpcs+=("$rpc"); domains+=("$domain"); heights+=("$(jq -r '.result.sync_info.latest_block_height' "$status")")
done
(( ${#good_rpcs[@]} >= 2 )) || die rpc_quorum_conflict 'fewer than two readable RPC observations attest the selected chain'
[[ "$(printf '%s\n' "${domains[@]}" | LC_ALL=C sort -u | wc -l)" -ge 2 ]] || die rpc_fault_domain_alias 'two RPC URLs resolve to one fault domain'

# Keep one endpoint per domain. Extra mirrors cannot turn a one-domain quorum
# into two observations.
declare -a quorum_rpcs=() quorum_domains=()
for i in "${!good_rpcs[@]}"; do
  if [[ " ${quorum_domains[*]} " != *" ${domains[$i]} "* ]]; then
    quorum_rpcs+=("${good_rpcs[$i]}"); quorum_domains+=("${domains[$i]}")
  fi
done
quorum_rpcs=("${quorum_rpcs[@]:0:2}"); quorum_domains=("${quorum_domains[@]:0:2}")
mapfile -t ordered_heights < <(printf '%s\n' "${heights[@]}" | LC_ALL=C sort -n)
tip="${ordered_heights[0]}"; (( tip > period )) || die trust_expired 'network tip is below the configured trust window'
trust_height=$((tip - period))

declare -a early_records=() trust_records=() applied_heights=()
for rpc in "${quorum_rpcs[@]}"; do
  for checkpoint in "early:$early_height" "trust:$trust_height"; do
    IFS=: read -r label height <<<"$checkpoint"
    file="$tmp/$label-${#early_records[@]}-$height.json"
    curl -fsS --connect-timeout 5 --max-time 15 "${rpc%/}/block?height=$height" >"$file" 2>/dev/null || die rpc_quorum_conflict "cannot read $label checkpoint from $rpc"
    record="$(record_from_block <"$file")" || die rpc_quorum_conflict "malformed $label checkpoint from $rpc"
    case "$label" in early) early_records+=("$record");; trust) trust_records+=("$record");; esac
  done
  api="$(api_for_rpc "$rpc")"
  applied="$tmp/applied-${#applied_heights[@]}.json"
  curl -fsS --connect-timeout 5 --max-time 15 "$api/chain-api/cosmos/upgrade/v1beta1/applied_plan/v${GDC_NETWORK_CORE_VERSION}" >"$applied" 2>/dev/null || die rpc_quorum_conflict "cannot read applied upgrade marker from $api"
  applied_height="$(jq -er '.height|tonumber' "$applied")" || die rpc_quorum_conflict "malformed applied upgrade marker from $api"
  applied_heights+=("$applied_height")
done
early="$(one_record early "${early_records[@]}")"
trust="$(one_record trust "${trust_records[@]}")"
post_height="$(one_record post_upgrade_height "${applied_heights[@]}")"; post_height=$((post_height + 1))
declare -a post_records=() snapshot_records=()
for rpc in "${quorum_rpcs[@]}"; do
  post_file="$tmp/post-${#post_records[@]}.json"
  curl -fsS --connect-timeout 5 --max-time 15 "${rpc%/}/block?height=$post_height" >"$post_file" 2>/dev/null || die rpc_quorum_conflict "cannot read post-upgrade checkpoint from $rpc"
  post_records+=("$(record_from_block <"$post_file")")
  snapshots="$tmp/snapshots-${#snapshot_records[@]}.json"
  curl -fsS --connect-timeout 5 --max-time 15 "${rpc%/}/snapshots" >"$snapshots" 2>/dev/null || die snapshot_unavailable "no snapshot inventory at $rpc"
  snapshot_records+=("$(jq -cer --argjson post "$post_height" '
    (.result.snapshots // [])
    | map(select((.height|tonumber) > $post and (.format|tonumber) > 0 and (.chunks|tonumber) > 0))
    | map({height:(.height|tonumber),format:(.format|tonumber),chunks:(.chunks|tonumber),hash:(.hash|ascii_downcase)})
    | sort_by(.height,.format,.chunks,.hash) | last
  ' "$snapshots")")
done
post="$(one_record post_upgrade "${post_records[@]}")"
snapshot="$(one_record snapshot "${snapshot_records[@]}")"
[[ "$snapshot" != null ]] || die snapshot_unavailable 'no compatible post-upgrade snapshot is available from two independent domains'
[[ "$(jq -r '.hash | type == "string" and test("^[0-9a-f]{64}$")' <<<"$snapshot")" == true ]] || die snapshot_incompatible 'snapshot format or hash is unsupported'

expires_at="$(date -u -d "+${ttl} seconds" +%FT%TZ)"
empty_digest="$(printf '' | sha256sum | awk '{print $1}')"
mkdir -p "$(dirname "$RECEIPT")" "$(dirname "$ENV_FILE")"
jq -n \
  --arg profile "$GDC_RELEASE_PROFILE" --arg fingerprint "$GDC_NETWORK_FINGERPRINT" --arg profile_hash "$(profile_hash)" \
  --arg core_version "$GDC_NETWORK_CORE_VERSION" --arg core_commit "$GDC_NETWORK_CORE_COMMIT" \
  --arg dapi_version "$GDC_NETWORK_DAPI_VERSION" --arg dapi_commit "$GDC_NETWORK_DAPI_COMMIT" --arg image "$INFERENCED_IMAGE" \
  --arg chain "$GDC_NETWORK_CHAIN_ID" --arg genesis "$GDC_NETWORK_GENESIS_SHA256" --arg expires "$expires_at" \
  --argjson early "$early" --argjson post "$post" --argjson trust "$trust" --argjson snapshot "$snapshot" \
  --argjson domains "$(for i in "${!quorum_rpcs[@]}"; do jq -cn --arg id "${quorum_domains[$i]}" --arg rpc "${quorum_rpcs[$i]}" --arg chain "$GDC_NETWORK_CHAIN_ID" --arg genesis "$GDC_NETWORK_GENESIS_SHA256" '{id:$id,rpc_url:$rpc,chain_id:$chain,genesis_sha256:$genesis}'; done | jq -s .)" \
  --arg empty "$empty_digest" \
  '{schema_version:1,kind:"gdc-host-join-lineage-preflight",runtime:{observed_runtime_profile:$profile,network_fingerprint:$fingerprint,profile_hash:$profile_hash,core_version:$core_version,core_commit:$core_commit,dapi_version:$dapi_version,dapi_commit:$dapi_commit,image_digest:($image|split("@")[1])},bootstrap:{mode:"state_sync",chain_id:$chain,genesis_sha256:$genesis,trust:($trust+{expires_at:$expires}),snapshot:{rpc_url:$domains[0].rpc_url,height:$snapshot.height,format:"cometbft_state_sync",runtime_compatible:true}},fault_domains:$domains,checkpoints:{early:$early,post_upgrade:$post,trust:$trust},staging:{previous_deployment_digest:$empty,rendered_config_digest:$empty,compose_validated:false},signer:{state:"PREPARED",tmkms_monotonic:true},result:{terminal_state:"prepared",category:"none",resume:"safe_exact_resume"}}' >"$RECEIPT"
{
  printf 'GDC_JOIN_BOOTSTRAP_MODE=%q\n' state_sync
  printf 'GDC_JOIN_TRUST_HEIGHT=%q\n' "$(jq -r .height <<<"$trust")"
  printf 'GDC_JOIN_TRUST_HASH=%q\n' "$(jq -r .block_id <<<"$trust")"
  printf 'GDC_JOIN_SNAPSHOT_HEIGHT=%q\n' "$(jq -r .height <<<"$snapshot")"
  printf 'GDC_JOIN_RPC_SERVER_1=%q\n' "${quorum_rpcs[0]}/"
  printf 'GDC_JOIN_RPC_SERVER_2=%q\n' "${quorum_rpcs[1]}/"
  printf 'GDC_JOIN_TRUSTED_BLOCK_PERIOD=%q\n' "$period"
  printf 'GDC_JOIN_LINEAGE_RECEIPT=%q\n' "$RECEIPT"
} >"$ENV_FILE"
chmod 0600 "$RECEIPT" "$ENV_FILE"
printf 'PASS JOIN lineage preflight mode=state_sync trust_height=%s snapshot_height=%s fault_domains=%s receipt=%s\n' "$(jq -r .height <<<"$trust")" "$(jq -r .height <<<"$snapshot")" "${#quorum_rpcs[@]}" "$RECEIPT"
