#!/usr/bin/env bash
# Resolve the cold-JOIN state-acquisition decision before software download or
# any Host operation. Bootstrap v1 deliberately contains no mutable trust or
# snapshot data, so this receipt records only observations made for this run.
set -Eeuo pipefail

usage() { echo "Usage: $0 --bootstrap-file FILE --composition-env FILE --receipt FILE --env FILE" >&2; }
die() {
  if [[ -n "${GDC_JOIN_LINEAGE_FAILURE_FILE:-}" ]]; then
    umask 077
    printf '%s\n' "$1" >"$GDC_JOIN_LINEAGE_FAILURE_FILE"
  fi
  printf 'lineage_%s: %s\n' "$1" "$2" >&2; exit 1
}
BOOTSTRAP=''; COMPOSITION=''; RECEIPT=''; ENV_FILE=''
while (($#)); do case "$1" in
  --bootstrap-file) BOOTSTRAP="${2:-}"; shift 2 ;;
  --composition-env) COMPOSITION="${2:-}"; shift 2 ;;
  --receipt) RECEIPT="${2:-}"; shift 2 ;;
  --env) ENV_FILE="${2:-}"; shift 2 ;;
  *) usage; exit 2 ;;
esac; done
[[ -r "$BOOTSTRAP" && -r "$COMPOSITION" && -n "$RECEIPT" && -n "$ENV_FILE" ]] || { usage; exit 2; }
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
command -v curl >/dev/null || die dependency 'curl is required'
command -v jq >/dev/null || die dependency 'jq is required'
"$ROOT/scripts/network-bootstrap.sh" verify "$BOOTSTRAP" >/dev/null
# Generated by the observer only after its immutable profile mapping checks.
# shellcheck disable=SC1090
source "$COMPOSITION"
[[ "${GDC_NETWORK_FINGERPRINT:-}" =~ ^[0-9a-f]{64}$ ]] || die configuration 'missing network fingerprint'
[[ "${GDC_NETWORK_CHAIN_ID:-}" == "$(jq -r .chain_id "$BOOTSTRAP")" ]] || die configuration 'composition and Bootstrap chain IDs differ'
[[ "${GDC_NETWORK_GENESIS_SHA256:-}" == "$(jq -r .genesis.sha256 "$BOOTSTRAP")" ]] || die configuration 'composition and Bootstrap Genesis digests differ'
source "$ROOT/scripts/profile.sh"
load_profiles

period="${GDC_JOIN_TRUSTED_BLOCK_PERIOD:-2000}"
early_height="${GDC_JOIN_EARLY_CHECKPOINT_HEIGHT:-5}"
ttl="${GDC_JOIN_PREFLIGHT_TTL_SECONDS:-600}"
[[ "$period" =~ ^[1-9][0-9]*$ && "$early_height" =~ ^[1-9][0-9]*$ && "$ttl" =~ ^[1-9][0-9]*$ ]] || die configuration 'trust period, early checkpoint and receipt TTL must be positive'
tmp="$(mktemp -d)"; trap 'rm -rf -- "$tmp"' EXIT

# Tests can supply a closed host=id map. Production always resolves a host to
# its IPv4 address. The map avoids treating two test aliases as independent.
fault_domain() {
  local host="$1" entry
  if [[ -n "${GDC_JOIN_FAULT_DOMAIN_MAP:-}" ]]; then
    IFS=, read -r -a entries <<<"$GDC_JOIN_FAULT_DOMAIN_MAP"
    for entry in "${entries[@]}"; do [[ "$entry" == "$host="* ]] && { printf '%s' "${entry#*=}"; return; }; done
    return 1
  fi
  getent ahostsv4 "$host" 2>/dev/null | awk 'NR == 1 {print $1}'
}

record_from_block() {
  jq -cer '{height:(.result.block.header.height|tonumber),block_id:(.result.block_id.hash|ascii_downcase),app_hash:(.result.block.header.app_hash|ascii_downcase)}'
}
one_record() {
  local label="$1"; shift
  local -a unique=()
  mapfile -t unique < <(printf '%s\n' "$@" | LC_ALL=C sort -u)
  (( ${#unique[@]} == 1 )) || die rpc_quorum_conflict "independent RPCs disagree at $label"
  printf '%s' "${unique[0]}"
}
api_for_rpc() { local rpc="$1"; printf '%s' "${rpc%/chain-rpc}"; }
p2p_for_rpc() {
  local rpc="$1" index node_id p2p
  index="$(jq -r --arg rpc "$rpc" '.seeds | to_entries[] | select(.value.rpc == $rpc) | .key' "$BOOTSTRAP" | head -1)"
  [[ "$index" =~ ^[0-9]+$ ]] || return 1
  node_id="$(jq -r ".seeds[$index].node_id" "$BOOTSTRAP")"
  p2p="$(jq -r ".seeds[$index].p2p" "$BOOTSTRAP")"
  [[ "$node_id" =~ ^[0-9a-f]{40}$ && "$p2p" =~ ^tcp://[A-Za-z0-9.-]+:[0-9]{2,5}$ ]] || return 1
  printf '%s@%s' "$node_id" "$p2p"
}

mapfile -t rpcs < <(jq -r '.seeds[].rpc' "$BOOTSTRAP")
(( ${#rpcs[@]} >= 2 )) || die rpc_quorum_conflict 'Bootstrap has fewer than two RPC seeds'
declare -a good_rpcs=() domains=() heights=()
for rpc in "${rpcs[@]}"; do
  host="${rpc#https://}"; host="${host%%/*}"
  domain="$(fault_domain "$host" || true)"
  [[ "$domain" =~ ^[A-Za-z0-9._:-]+$ ]] || die rpc_quorum_conflict "cannot establish fault domain for $host"
  status="$tmp/status-${#good_rpcs[@]}.json"
  curl -fsS --connect-timeout 5 --max-time 15 "${rpc%/}/status" >"$status" 2>/dev/null || continue
  jq -e --arg chain "$GDC_NETWORK_CHAIN_ID" '.result.node_info.network == $chain and (.result.sync_info.latest_block_height|tonumber) > 0' "$status" >/dev/null || continue
  good_rpcs+=("$rpc"); domains+=("$domain"); heights+=("$(jq -r '.result.sync_info.latest_block_height' "$status")")
done
[[ "$(printf '%s\n' "${domains[@]}" | LC_ALL=C sort -u | wc -l)" -ge 2 ]] || die rpc_fault_domain_alias 'two RPC URLs resolve to one fault domain'
(( ${#good_rpcs[@]} >= 2 )) || die rpc_quorum_conflict 'fewer than two readable RPC observations attest the selected chain'

# Choose the highest attested tip. A status height is only a proposal: two
# independent domains must serve the same header/AppHash there. A failed block
# read is a non-vote, while a malformed successful response is unsafe. One
# outlier is tolerated; A,A,B,C is not.
declare -a quorum_rpcs=() quorum_domains=()
select_tip_quorum() {
  local candidate i file record best='' best_count=0 group_count=0 responding count
  local -a records=() indices=() groups=() candidates=() candidate_domains=()
  mapfile -t candidates < <(printf '%s\n' "${heights[@]}" | LC_ALL=C sort -nr -u)
  for candidate in "${candidates[@]}"; do
    records=(); indices=(); candidate_domains=()
    for i in "${!good_rpcs[@]}"; do
      (( heights[i] >= candidate )) || continue
      [[ " ${candidate_domains[*]} " == *" ${domains[$i]} "* ]] && continue
      file="$tmp/tip-${candidate}-${i}.json"
      curl -fsS --connect-timeout 5 --max-time 15 "${good_rpcs[$i]%/}/block?height=$candidate" >"$file" 2>/dev/null || continue
      record="$(record_from_block <"$file")" || die rpc_quorum_conflict "malformed tip checkpoint from ${good_rpcs[$i]}"
      records+=("$record"); indices+=("$i"); candidate_domains+=("${domains[$i]}")
    done
    (( ${#records[@]} >= 2 )) || continue
    mapfile -t groups < <(printf '%s\n' "${records[@]}" | LC_ALL=C sort | uniq -c)
    best=''; best_count=0; group_count=0
    for group in "${groups[@]}"; do
      count="$(awk '{print $1}' <<<"$group")"
      # shellcheck disable=SC2001 # preserve the JSON record after uniq's count
      record="$(sed 's/^[[:space:]]*[0-9][0-9]*[[:space:]]*//' <<<"$group")"
      if (( count >= 2 )); then
        group_count=$((group_count + 1))
        if (( count > best_count )); then best="$record"; best_count="$count"; fi
      fi
    done
    responding="${#records[@]}"
    (( group_count == 1 && best_count >= 2 && responding - best_count <= 1 )) || continue
    quorum_rpcs=(); quorum_domains=()
    for i in "${!records[@]}"; do
      [[ "${records[$i]}" == "$best" ]] || continue
      quorum_rpcs+=("${good_rpcs[${indices[$i]}]}")
      quorum_domains+=("${domains[${indices[$i]}]}")
    done
    tip="$candidate"
    return 0
  done
  return 1
}
select_tip_quorum || die rpc_quorum_conflict 'no unique 2-of-3 RPC header/AppHash quorum exists at a common tip'
(( tip > period )) || die trust_expired 'quorum-attested network tip is below the configured trust window'
trust_height=$((tip - period))

declare -a early_records=() trust_records=() applied_heights=()
for rpc in "${quorum_rpcs[@]}"; do
  for checkpoint in "early:$early_height" "trust:$trust_height"; do
    IFS=: read -r label height <<<"$checkpoint"
    file="$tmp/$label-${#early_records[@]}-$height.json"
    curl -fsS --connect-timeout 5 --max-time 15 "${rpc%/}/block?height=$height" >"$file" 2>/dev/null || die rpc_quorum_conflict "cannot read $label checkpoint from $rpc"
    record="$(record_from_block <"$file")" || die rpc_quorum_conflict "malformed $label checkpoint from $rpc"
    case "$label" in early) early_records+=("$record");; trust) trust_records+=("$record");; esac
  done
  api="$(api_for_rpc "$rpc")"
  applied="$tmp/applied-${#applied_heights[@]}.json"
  curl -fsS --connect-timeout 5 --max-time 15 "$api/chain-api/cosmos/upgrade/v1beta1/applied_plan/v${GDC_NETWORK_CORE_VERSION}" >"$applied" 2>/dev/null || die rpc_quorum_conflict "cannot read applied upgrade marker from $api"
  applied_height="$(jq -er '.height|tonumber' "$applied")" || die rpc_quorum_conflict "malformed applied upgrade marker from $api"
  applied_heights+=("$applied_height")
done
early="$(one_record early "${early_records[@]}")"
trust="$(one_record trust "${trust_records[@]}")"
post_height="$(one_record post_upgrade_height "${applied_heights[@]}")"; post_height=$((post_height + 1))
declare -a post_records=() snapshot_providers=()
for rpc in "${quorum_rpcs[@]}"; do
  post_file="$tmp/post-${#post_records[@]}.json"
  curl -fsS --connect-timeout 5 --max-time 15 "${rpc%/}/block?height=$post_height" >"$post_file" 2>/dev/null || die rpc_quorum_conflict "cannot read post-upgrade checkpoint from $rpc"
  post_records+=("$(record_from_block <"$post_file")")
  provider="$(p2p_for_rpc "$rpc")" || die configuration "Bootstrap has no valid P2P provider for quorum RPC $rpc"
  snapshot_providers+=("$provider")
done
post="$(one_record post_upgrade "${post_records[@]}")"
# CometBFT v0.38 has no HTTP /snapshots RPC. Snapshot metadata and chunks are
# discovered through P2P channels and ABCI; actual availability is therefore
# proven by the signerless canary, not by a made-up HTTP endpoint.
snapshot="$(printf '%s\n' "${snapshot_providers[@]}" | jq -R . | jq -s '{discovery:"p2p_canary_pending",providers:.}')"

expires_at="$(date -u -d "+${ttl} seconds" +%FT%TZ)"
empty_digest="$(printf '' | sha256sum | awk '{print $1}')"
mkdir -p "$(dirname "$RECEIPT")" "$(dirname "$ENV_FILE")"
jq -n \
  --arg profile "$GDC_RELEASE_PROFILE" --arg fingerprint "$GDC_NETWORK_FINGERPRINT" --arg profile_hash "$(profile_hash)" \
  --arg core_version "$GDC_NETWORK_CORE_VERSION" --arg core_commit "$GDC_NETWORK_CORE_COMMIT" \
  --arg dapi_version "$GDC_NETWORK_DAPI_VERSION" --arg dapi_commit "$GDC_NETWORK_DAPI_COMMIT" --arg image "$INFERENCED_IMAGE" \
  --arg chain "$GDC_NETWORK_CHAIN_ID" --arg genesis "$GDC_NETWORK_GENESIS_SHA256" --arg expires "$expires_at" \
  --argjson early "$early" --argjson post "$post" --argjson trust "$trust" --argjson snapshot "$snapshot" \
  --argjson domains "$(for i in "${!quorum_rpcs[@]}"; do jq -cn --arg id "${quorum_domains[$i]}" --arg rpc "${quorum_rpcs[$i]}" --arg chain "$GDC_NETWORK_CHAIN_ID" --arg genesis "$GDC_NETWORK_GENESIS_SHA256" '{id:$id,rpc_url:$rpc,chain_id:$chain,genesis_sha256:$genesis}'; done | jq -s .)" \
  --arg empty "$empty_digest" \
  '{schema_version:1,kind:"gdc-host-join-lineage-preflight",runtime:{observed_runtime_profile:$profile,network_fingerprint:$fingerprint,profile_hash:$profile_hash,core_version:$core_version,core_commit:$core_commit,dapi_version:$dapi_version,dapi_commit:$dapi_commit,image_digest:($image|split("@")[1])},bootstrap:{mode:"state_sync",chain_id:$chain,genesis_sha256:$genesis,trust:($trust+{expires_at:$expires}),snapshot:$snapshot},fault_domains:$domains,checkpoints:{early:$early,post_upgrade:$post,trust:$trust},staging:{previous_deployment_digest:$empty,rendered_config_digest:$empty,compose_validated:false},signer:{state:"PREPARED",tmkms_monotonic:false},result:{terminal_state:"prepared",category:"none",resume:"safe_exact_resume"}}' >"$RECEIPT"
{
  printf 'GDC_JOIN_BOOTSTRAP_MODE=%q\n' state_sync
  printf 'GDC_JOIN_TRUST_HEIGHT=%q\n' "$(jq -r .height <<<"$trust")"
  printf 'GDC_JOIN_TRUST_HASH=%q\n' "$(jq -r .block_id <<<"$trust")"
  printf 'GDC_JOIN_SNAPSHOT_PEERS=%q\n' "$(IFS=,; echo "${snapshot_providers[*]}")"
  printf 'GDC_JOIN_RPC_SERVER_1=%q\n' "${quorum_rpcs[0]}/"
  printf 'GDC_JOIN_RPC_SERVER_2=%q\n' "${quorum_rpcs[1]}/"
  printf 'GDC_JOIN_TRUSTED_BLOCK_PERIOD=%q\n' "$period"
  printf 'GDC_JOIN_LINEAGE_RECEIPT=%q\n' "$RECEIPT"
} >"$ENV_FILE"
chmod 0600 "$RECEIPT" "$ENV_FILE"
printf 'PASS JOIN lineage preflight mode=state_sync trust_height=%s p2p_snapshot_providers=%s fault_domains=%s receipt=%s\n' "$(jq -r .height <<<"$trust")" "${#snapshot_providers[@]}" "${#quorum_rpcs[@]}" "$RECEIPT"
