#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PHASE="$ROOT/scripts/phase-join-acceptance.sh"

[[ -x "$PHASE" ]]
bash -n "$PHASE"
grep -Fq 'GDC_JOIN_EFFECTIVE_EPOCHS' "$ROOT/profiles/releases/v2026.07.23.lock"
grep -Fq 'GDC_JOIN_EFFECTIVE_TIMEOUT_SECONDS' "$ROOT/profiles/releases/v2026.07.23.lock"
grep -Fq 'GENESIS_HASH=UNAVAILABLE' "$PHASE"
grep -Fq 'deadline_epoch=0' "$PHASE"
grep -Fq 'topology_contains_node "$NODE"' "$PHASE"
! grep -Fq 'node_name "${1:-}"' "$PHASE"
grep -Fq 'or .participant.status == 1' "$PHASE"
grep -Fq 'record_join_state "$NODE" POC_ACCEPTED "$ADDRESS"' "$PHASE"
grep -Fq 'record_join_state "$NODE" VALIDATOR_EFFECTIVE "$ADDRESS"' "$PHASE"
grep -Fq 'record_join_state "$NODE" COMPLETE "$ADDRESS"' "$PHASE"
grep -Fq 'operator_mode:$operator_mode' "$PHASE"
grep -Fq 'operator_mode "independent-host"' "$PHASE"
grep -Fq 'KEY_FILE="$SECRETS/gateway.join-client-key"' "$PHASE"
grep -Fq 'mode 0600' "$PHASE"
grep -Fq 'separately scoped join client credential' "$PHASE"
grep -Fq 'gateway.join-client-key' "$ROOT/04-ops/create-gateway.sh"
grep -Fq 'gateway/join-client-key' "$ROOT/04-ops/render-ops.sh"
grep -Fq 'join_bootstrap_format=$JOIN_BOOTSTRAP_FORMAT' "$ROOT/04-ops/render-ops.sh"
grep -Fq 'Genesis profile does not match the selected release' "$ROOT/04-ops/render-ops.sh"
grep -Fq 'gateway/join-client-key' "$ROOT/scripts/fetch-join-bootstrap.sh"
grep -Fq 'join_bootstrap_format=$JOIN_BOOTSTRAP_FORMAT' "$ROOT/scripts/fetch-join-bootstrap.sh"
grep -Fq 'join_bootstrap_format=$JOIN_BOOTSTRAP_FORMAT' "$ROOT/scripts/prepare-join-role-config.sh"
grep -Fq 'GDC_JOIN_INFERENCE_TIMEOUT_SECONDS' "$PHASE"
grep -Fq '"$RUN/gateway-regression/completion.json" "$inference_timeout"' "$PHASE"
grep -Fq 'authenticated gateway regression did not complete:' "$PHASE"
grep -Fq 'curl_status=%s' "$PHASE"
grep -Fq "fetch_public_json 'current epoch group'" "$PHASE"
grep -Fq "fetch_public_json 'consensus validator set'" "$PHASE"
grep -Fq 'join acceptance cannot read epoch state from url=%s; retrying' "$PHASE"
grep -Fq '.local_id == $runtime_id' "$PHASE"
grep -Fq 'Host join: INCONCLUSIVE' "$PHASE"
grep -Fq 'Host join: FAIL' "$PHASE"
grep -Fq 'Host join: BLOCKED' "$PHASE"
grep -Fq 'Host join: PASS' "$PHASE"
grep -Fq 'cut -d, -f1 <"$KEY_FILE"' "$PHASE"
grep -Fq 'check-validation-weight-evidence.sh' "$PHASE"
grep -Fq 'validation-weight distribution is rejected' "$PHASE"
grep -Fq 'poc_accepted_once=false' "$PHASE"
grep -Fq 'retaining it through the stability window' "$PHASE"
grep -Fq 'poc-acceptance-observations.json' "$PHASE"
grep -Fq 'join_acceptance_state_initialize' "$PHASE"
grep -Fq 'join_acceptance_state_restore_strongest' "$PHASE"
grep -Fq 'join_acceptance_state_restore_distribution' "$PHASE"
grep -Fq 'join_acceptance_state_record_distribution' "$PHASE"
grep -Fq 'no canonical code=0 distribution transaction became readable before the eligibility deadline' "$PHASE"
grep -Fq 'join acceptance state is absent or bound to another Genesis, participant, or runtime' "$PHASE"
grep -Fq '[[ -s "$RUN/poc-acceptance-observations.json" ]] ||' "$PHASE"
grep -Fq '[[ -s "$RUN/poc-stage-traces.json" ]] ||' "$PHASE"
grep -Fq 'capture_poc_distribution_transactions' "$PHASE"
grep -Fq 'artifact_stage=$((stage + EPOCH_LENGTH))' "$PHASE"
grep -Fq "fetch_public_json 'inference epoch parameters'" "$PHASE"
grep -Fq 'artifact_public_matches_local == true' "$PHASE"
grep -Fq "artifact root is not populated yet" "$PHASE"
grep -Fq "fetch_public_json 'canonical PoC distribution index'" "$PHASE"
grep -Fq 'canonical PoC distribution block stage=$stage height=$height' "$PHASE"
grep -Fq 'canonical PoC distribution transaction stage=$stage height=$height tx=$tx_hash' "$PHASE"
grep -Fq 'LAST_PUBLIC_FETCH_FAILURE=' "$PHASE"
grep -Fq 'POC_DISTRIBUTION_READBACK_FAILURE=' "$PHASE"
grep -Fq 'canonical PoC distribution readback unavailable canonical_stage=%s%s' "$PHASE"
grep -Fq 'tx_hash=\(.tx_hash) tx_code=\(.tx_code) tx_height=\(.tx_height)' "$PHASE"
grep -Fq 'previous_stage=$((canonical_stage - EPOCH_LENGTH))' "$PHASE"
grep -Fq 'capture_poc_distribution_transactions "$previous_stage" || true' "$PHASE"
! grep -Fq 'done < <(curl -fsS --connect-timeout 5 --max-time 15' "$PHASE"
grep -Fq 'artifact_local="http://127.0.0.1:8000/v1/poc/artifacts/state' "$PHASE"
! grep -Fq 'artifact_local="http://127.0.0.1:9000/v1/poc/artifacts/state' "$PHASE"
grep -Fq -- "-w '%{http_code}' \"\$artifact_public\"" "$PHASE"
grep -Fq 'public PoC artifact unavailable canonical_stage=%s artifact_stage=%s url=%s http_status=%s curl_exit=%s curl_status=%s' "$PHASE"
grep -Fq '{unavailable:true,canonical_stage:$canonical_stage,artifact_stage:$artifact_stage,http_status:$http_status,response:$response}' "$PHASE"
grep -Fq 'MsgMLNodeWeightDistribution' "$PHASE"
grep -Fq 'chain-api/cosmos/tx/v1beta1/txs/$tx_hash' "$PHASE"
grep -Fq 'poc_distribution_tx_hash' "$PHASE"
grep -Fq 'poc_distribution_tx_code' "$PHASE"
grep -Fq 'and any(.[]; .tx_code == 0' "$PHASE"
grep -Fq "[.[] | select(.tx_code == 0)] | last.tx_hash" "$PHASE"
transactions='[{"tx_hash":"rejected","tx_code":1137,"tx_height":705,"scanned_height":705,"messages":[{"creator":"gonka1operator"}]},{"tx_hash":"accepted","tx_code":0,"tx_height":712,"scanned_height":712,"messages":[{"creator":"gonka1operator"}]}]'
jq -e --arg participant gonka1operator '
  any(.[]; .tx_code == 0 and .tx_height >= 700 and .scanned_height == .tx_height
    and any(.messages[]?; .creator == $participant))
' <<<"$transactions" >/dev/null
[[ "$(jq -er '[.[] | select(.tx_code == 0)] | last.tx_hash' <<<"$transactions")" == accepted ]]
grep -Fq 'write_phase_lineage "$RUN" "$CHAIN_ID" "$GENESIS_HASH"' "$PHASE"
grep -Fq 'GDC_JOIN_EFFECTIVE_EPOCHS' "$ROOT/profiles/releases/v2026.08.06.lock"
grep -Fq 'positive accepted PoC weight in the bounded window' "$PHASE"
grep -Fq 'epoch >= deadline_epoch' "$PHASE"
grep -Fq 'phase-join-acceptance.sh' "$ROOT/scripts/phase-join.sh"
grep -Fq 'GDC_JOIN_VERIFICATION:-false' "$ROOT/scripts/phase-join.sh"
grep -Fq 'operational join complete' "$ROOT/scripts/phase-join.sh"
! grep -Fq 'joined successfully' "$ROOT/scripts/phase-join.sh"
bash "$ROOT/scripts/test-join-acceptance-resume.sh"

echo 'PASS join acceptance state-machine contract'
