#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
deploy="$ROOT/scripts/deploy-telegram-bot.sh"

bash -n "$deploy"
grep -Fq "ssh -T \"\$BOT_HOST\" 'bash -s' <<'REMOTE'" "$deploy"
grep -Fq 'for host in "${GDC_NODES[@]}"; do' "$deploy"
grep -Fq '[[ "$host" == "$BOT_HOST" ]] && continue' "$deploy"
grep -Fq 'docker ps -q --filter name=gonka-devnet-bot-bot | xargs -r docker stop' "$deploy"
grep -Fq 'textfile_collector/telegram-bot.prom' "$deploy"
grep -Fq "docker info >/dev/null 2>&1' >/dev/null 2>&1 || continue" "$deploy"
grep -Fq 'docker compose up -d --build --force-recreate' "$deploy"
grep -Fq 'grep -qx gonka-devnet-bot-bot-1' "$deploy"
grep -Fq 'BOT_KEY_FILE="$SECRETS/gateway.telegram-client-key"' "$deploy"
grep -Fq 'BOT_API_BASE_URL="https://${API_HOST}/v1"' "$deploy"
grep -Fq 'Telegram consumer must run on the gateway Host' "$deploy"
grep -Fq 'GATEWAY_TIMEOUT_SECONDS=${GDC_TELEGRAM_GATEWAY_TIMEOUT_SECONDS:-30}' "$deploy"
grep -Fq 'TELEGRAM_POLL_TIMEOUT_SECONDS=${GDC_TELEGRAM_POLL_TIMEOUT_SECONDS:-35}' "$deploy"
! grep -Fq 'GDC_TELEGRAM_BOT_API_BASE_URL' "$deploy"
grep -Fq 'HTTP_HOST=127.0.0.1' "$deploy"
grep -Fq 'network_mode: host' "$ROOT/scripts/telegram-bot/compose.yaml"
! grep -Fq 'ports:' "$ROOT/scripts/telegram-bot/compose.yaml"
grep -Fq 'BOT_INTERNAL_TOKEN_FILE="$SECRETS/telegram.conversation-api-token"' "$deploy"
grep -Fq 'GATEWAY_API_KEY=$BOT_GATEWAY_API_KEY' "$deploy"
grep -Fq 'INTERNAL_API_TOKEN=$BOT_INTERNAL_API_TOKEN' "$deploy"
grep -Fq 'VERIFY_TIMEOUT_SECONDS="${GDC_TELEGRAM_CONSUMER_VERIFY_TIMEOUT_SECONDS:-300}"' "$deploy"
grep -Fq 'Telegram consumer runtime is not ready; retrying before deadline=%ss' "$deploy"
grep -Fq '<"$ROOT/scripts/telegram-consumer-probe-loop.sh"' "$deploy"
grep -Fq 'X-Request-Deadline-Ms' "$ROOT/scripts/telegram-bot/bot.py"
[[ "$(grep -Fc 'timeout "$remaining" ssh -T "$BOT_HOST"' "$deploy")" == 2 ]]
grep -Fq 'Telegram consumer inference is not ready health=%s' "$ROOT/scripts/phase-telegram-consumer.sh"
grep -Fq '[[ "$action" != verify ]]' "$ROOT/scripts/phase-telegram-consumer.sh"
grep -Fq 'probe completed but readiness was not updated' "$ROOT/scripts/telegram-consumer-probe-loop.sh"
grep -Fq 'Telegram consumer inference probe failed without safe retry attempt=%s reason=%s' "$ROOT/scripts/telegram-consumer-probe-loop.sh"
! grep -Fq 'Telegram consumer probe did not complete' "$deploy"
grep -Fq 'HEALTH_MAX_AGE_SECONDS=' "$deploy"
! grep -Eq 'gateway-key-pool|POOL_SOURCE|key issuer' "$deploy"

grep -Fq '@telegram_consumer path /status/telegram-consumer' "$ROOT/04-ops/edge-node/PublicCaddyfile"
grep -Fq 'reverse_proxy https://{$TELEGRAM_BOT_PUBLIC_HOST}' "$ROOT/04-ops/edge-node/PublicCaddyfile"
grep -Fq '@status_data {' "$ROOT/04-ops/edge-node/PublicCaddyfile"
grep -Fq '@telegram_consumer_health_from_observer' "$ROOT/04-ops/edge-node/Caddyfile"
grep -Fq '@telegram_metrics_from_monitoring' "$ROOT/04-ops/edge-node/Caddyfile"
grep -Fq 'remote_ip {$MONITORING_CIDR} {$PUBLIC_EDGE_CIDR}' "$ROOT/04-ops/edge-node/Caddyfile"
grep -Fq 'telegram_bot_public_host="$PUBLIC_EDGE_HOST"' "$ROOT/04-ops/edge-node/render-env.sh"
grep -Fq 'telegram_bot_public_host="$(node_public_host "$TELEGRAM_BOT_HOST")"' "$ROOT/04-ops/edge-node/render-env.sh"
grep -Fq 'job_name: telegram-consumer' "$ROOT/04-ops/render-ops.sh"
grep -Fq 'json("/status/telegram-consumer")' "$ROOT/04-ops/site/src/app.js"
grep -Fq 'link.href = cfg.telegramBot' "$ROOT/04-ops/site/src/app.js"
grep -Fq 'link.hidden = false' "$ROOT/04-ops/site/src/app.js"
! grep -Fq 'if (health.status !== "ok" || health.inference_ready !== true) return;' "$ROOT/04-ops/site/src/app.js"

grep -Fq './gdc.sh ops consumer telegram apply' "$ROOT/gdc.sh"
grep -Fq 'phase-telegram-consumer.sh' "$ROOT/gdc.sh"
grep -Fq 'sla="${2:-300s}"' "$ROOT/scripts/phase-telegram-consumer.sh"
grep -Fq '< "$ROOT/scripts/telegram-consumer-probe-loop.sh"' "$ROOT/scripts/phase-telegram-consumer.sh"
grep -Fq 'deadline=$(( $(date +%s) + sla_seconds ))' "$ROOT/scripts/telegram-consumer-probe-loop.sh"
grep -Fq 'probe_timeout=35' "$ROOT/scripts/telegram-consumer-probe-loop.sh"
grep -Fq 'gateway_pre_dispatch_rejected' "$ROOT/scripts/telegram-consumer-probe-loop.sh"
grep -Fq 'X-GDC-Admission' "$ROOT/scripts/telegram-bot/bot.py"
! grep -Fq 'gateway_returned_HTTP_429|gateway_returned_HTTP_502|gateway_returned_HTTP_503|gateway_returned_HTTP_504|probe_timeout' "$ROOT/scripts/telegram-consumer-probe-loop.sh"
grep -Fq 'inference did not recover within %ss attempts=%s last_reason=%s' "$ROOT/scripts/telegram-consumer-probe-loop.sh"
! grep -Fq 'timeout "$sla_seconds" docker exec' "$ROOT/scripts/telegram-consumer-probe-loop.sh"
grep -Fq 'gateway access-key ensure telegram' "$ROOT/gdc.sh"
grep -Fq 'phase-gateway-access-key.sh' "$ROOT/gdc.sh"
! grep -Eq 'telegram-key-probe|telegram-bot\)' "$ROOT/gdc.sh"

printf 'PASS Telegram conversation consumer deployment contract\n'
