FROM node:26-slim@sha256:c0753125a3789977aefe869cbebccf70e3cfd7ea84ca48547458f02e4f1d7146

RUN apt-get update \
    && apt-get install -y --no-install-recommends git jq make rsync \
    && rm -rf /var/lib/apt/lists/*

USER node
WORKDIR /workspace
