"""gcheck gateway-load testenv without Docker: config, compose patch, parsing, rates, verdicts, CLI and cleanup."""

import contextlib
import io
import json
import os
import subprocess
import tempfile
import unittest
from unittest import mock

from gonka_check import cli
from gonka_check.gateway import report, stand, stress, testenv
from tests.test_gateway_stand import FakeGateway

COMMIT = stress.TAG_COMMIT
CONFIG = """# Auto-generated by gencompose
chain_id: gonka-test
params:
    max_nonce: 20000
participants:
    - address: gonka1aaa
      inference_url: http://versiond-router:8080
    - address: gonka1bbb
      inference_url: http://versiond-router:8080
escrows:
    - id: 1
      slots:
        - gonka1aaa
        - gonka1bbb
hosts:
    - id: versiond-0
      private_key_hex: 01
      address: gonka1aaa
      url: http://versiond-router:8080
      key_name: versiond-0
    - id: versiond-1
      private_key_hex: 02
      address: gonka1bbb
      url: http://versiond-router:8080
      key_name: versiond-1
user:
    address: gonka1ccc
"""


def compose_model():
    """A cut of `docker compose config --format json` of a gencompose file with two hosts."""
    def service(image, **extra):
        out = {"build": {"context": "/src", "dockerfile": "Dockerfile"}, "image": image, "environment": {},
               "networks": {"testenv": {"ipv4_address": "172.30.77.9"}}, "restart": "unless-stopped",
               "ports": [{"mode": "ingress", "host_ip": "127.0.0.1", "target": 1, "published": "1", "protocol": "tcp"}]}
        out.update(extra)
        return out

    hosts = {"versiond-%d" % i: service("devshard-versiond:latest", environment={"KEY_NAME": "versiond-%d" % i},
                                       networks={"testenv": {"ipv4_address": "172.30.77.1%d" % i,
                                                             "aliases": ["versiond-pool"]}},
                                       depends_on={"mock-chain": {"condition": "service_healthy"}})
             for i in range(2)}
    return {"name": "x", "networks": {"testenv": {"name": "x_testenv"}}, "services": dict(
        hosts, **{"devshard-postgres": {"image": "postgres:16-alpine"},
                  "mock-chain": service("devshard-mock-chain:latest"),
                  "mock-dapi": service("devshard-mock-dapi:latest", environment={"MOCK_DAPI_BINARY_DIR": "/b"}),
                  "mock-openai": service("devshard-mock-openai:latest"),
                  "versiond-router": service("devshard-versiond-router:latest", environment={
                      "GONKA_HA": "true", "VERSIOND_ROUTING_ACTIVATION_MIN_READY": "2",
                      "VERSIOND_ROUTING_CATALOG_POLL_SECONDS": "1"}, depends_on=["versiond-0", "devshard-postgres"]),
                  "devshardctl": service("devshard-runtime:latest", environment={
                      "DEVSHARD_PORT": "38081", "DEVSHARD_ADMIN_API_KEY": "testenv-citest-admin"},
                      depends_on={"devshard-postgres": {"condition": "service_started"}})})}


class Fake(FakeGateway):
    """devshardctl of a testenv stack: heartbeat metrics, unquarantine, finalize with slot signatures."""

    def __init__(self, cap=None, groups=8, quorum_reached=True, quarantined=0, **kw):
        super().__init__(cap=cap, **kw)
        self.groups, self.quorum_reached, self.quarantined = groups, quorum_reached, quarantined
        self.unquarantined, self.heartbeats = [], 0

    def reply(self, method, path):
        with self.lock:
            if method == "GET" and path == "/metrics":
                self.heartbeats += 1
                return 200, ("process_cpu_seconds_total %.2f\nprocess_resident_memory_bytes %d\n"
                             'devshard_gateway_heightsync_cadence_events_total{devshard_id="1",'
                             'event="heartbeat_opened"} %d\n' % (self.cpu, 90 * 2 ** 20, self.heartbeats))
            if method == "GET" and path == "/v1/status" and self.cap is None:
                self.nonce += self.groups + 1 if self.chats else 0
                return 200, {"nonce": self.nonce, "phase": "active"}
            if method == "POST" and path == "/v1/admin/participants/unquarantine":
                self.unquarantined.append(path)
                self.quarantined = 0
                return 200, {"cleared": True}
            if method == "POST" and path == "/v1/chat/completions" and self.quarantined:
                return 503, {"error": {"message": "no live host capacity"}}
            if method == "POST" and path == "/v1/finalize" and not self.quorum_reached:
                return 500, {"error": {"message": "insufficient signatures: 0/%d weight" % stand.quorum(self.groups)}}
            if method == "POST" and path == "/v1/finalize":
                signatures = [{"slot_id": i % self.groups, "signature": "x"} for i in range(self.groups + 2)]
                return 200, {"nonce": self.nonce + self.groups + 1, "signatures": signatures,
                             "host_stats": [{"slot_id": i} for i in range(self.groups)]}
        return super().reply(method, path)


def summary(mode="drive", final=None, samples=None, drive_reason=testenv.ROUTED_STOP, **extra):
    drive = None
    if mode == "drive":
        drive = testenv.Drive("http://127.0.0.1:1", 1, testenv.ROUTING_STOP, "t")
        drive.codes, drive.reason = {200: 16000}, drive_reason
    warm = testenv.Drive("http://127.0.0.1:1", 1, 0, "t")
    warm.codes = {200: 3 if mode == "dry-run" else 20}
    if samples is None:
        samples = [sample("warm", 0, 30), sample("drive", 5, 1000), sample("drive", 2005, 19800),
                   sample("quiet", 2010, 19800, heartbeats=0, last=19800),
                   sample("quiet", 2310, 20450, heartbeats=10, last=19869, cap=40),
                   sample("final", 2400, 20515, heartbeats=10, last=19869, cap=40)]
    if final is None:
        final = {"code": 200, "seconds": 2.5, "weight": 64, "quorum": 43, "signatures": 64, "nonce": 20515}
    return testenv.summarize(64, 4, 8, mode, warm, drive, samples, final, **extra)


def sample(phase, t_s, nonce, heartbeats=None, last=None, cap=0):
    hosts = [{"host": i, "cpu_pct": 10.0 + i, "mem_mb": 100.0 + i, "write_mb": 1.0, "last_diff": last}
             for i in range(4)]
    return {"phase": phase, "t_s": float(t_s), "nonce": nonce, "cpu_s": t_s / 10, "rss_mb": 90.0, "cpu_pct": 20.0,
            "mem_mb": 95.0, "rx_mb": 1.0, "tx_mb": 2.0, "write_mb": 3.0, "storage_mb": 4.0, "heartbeats": heartbeats,
            "abandoned": 1 if heartbeats else 0, "cap_lines": cap, "dead_lines": cap, "hosts": hosts,
            "hosts_cpu_pct": 46.0, "hosts_mem_mb": 406.0, "host_last_min": last, "host_last_max": last}


class Config(unittest.TestCase):
    def test_skeleton_sets_the_cap_the_rate_and_one_identity_per_host(self):
        data = json.loads(json.dumps(testenv.skeleton(64, 4, "/cache/devshardd", "v5.0.2", 78)))
        self.assertEqual((20000, 1000), (data["params"]["max_nonce"], data["params"]["validation_rate"]))
        self.assertEqual(["versiond-%d" % i for i in range(4)], [host["key_name"] for host in data["hosts"]])
        self.assertEqual({"TODO"}, {host["private_key_hex"] for host in data["hosts"]})
        self.assertEqual(64, data["escrow"]["slots"])
        self.assertGreaterEqual(data["escrows"][0]["amount"], 20000 * 100000)
        self.assertEqual({"mode": "multi", "version_name": "v5", "binary_version": "v5.0.2",
                          "host_binary_mount": "/cache/devshardd", "poll_interval": "60s"}, data["versiond"])
        self.assertEqual({"subnet": "172.30.78.0/24", "base_ip": "172.30.78"}, data["network"])

    def test_participants_get_their_own_host_urls(self):
        text, addresses = testenv.direct_urls(CONFIG)
        self.assertEqual(["gonka1aaa", "gonka1bbb"], addresses)
        self.assertIn("      inference_url: http://versiond-0:8080\n    - address: gonka1bbb\n"
                      "      inference_url: http://versiond-1:8080\n", text)
        self.assertEqual(2, text.count("url: http://versiond-router:8080"))
        with self.assertRaisesRegex(testenv.TestenvError, "1 participant URLs for 2 hosts"):
            testenv.direct_urls(CONFIG.replace("    - address: gonka1bbb\n      inference_url: "
                                               "http://versiond-router:8080\n", ""))
        with self.assertRaisesRegex(testenv.TestenvError, "no participants"):
            testenv.direct_urls("hosts:\n    - id: versiond-0\n")

    def test_compose_runs_prebuilt_images_on_loopback_without_postgres(self):
        model = compose_model()
        spec = testenv.patch_compose(model, "gcheck-tenv-ab12-g8", COMMIT, "1000:1000")
        services = spec["services"]
        self.assertNotIn("devshard-postgres", services)
        self.assertEqual("gcheck-tenv-ab12-g8", spec["name"])
        self.assertIn("devshard-postgres", model["services"])
        for name, service in services.items():
            kind = "versiond" if name.startswith("versiond-") and name[-1].isdigit() else name
            self.assertEqual(testenv.image(kind, COMMIT), service["image"])
            self.assertEqual("gcheck-tenv-ab12-g8-" + name, service["container_name"])
            self.assertEqual({"driver": "local", "options": {"max-size": "20m", "max-file": "3"}}, service["logging"])
            self.assertNotIn("build", service)
            self.assertNotIn("cpuset", service)
            self.assertEqual("no", service["restart"])
            self.assertNotIn("devshard-postgres", service.get("depends_on") or [])
            if name != "devshardctl":
                self.assertNotIn("ports", service)
        gateway = services["devshardctl"]
        self.assertEqual([{"target": 38081, "host_ip": "127.0.0.1", "protocol": "tcp"}], gateway["ports"])
        self.assertEqual("1000:1000", gateway["user"])
        self.assertEqual({"DEVSHARD_PORT": "38081", "DEVSHARD_ADMIN_API_KEY": stand.ADMIN_KEY,
                          "DEVSHARD_ESCROW_ROTATION_ENABLED": "false", "DEVSHARD_LOG_LEVEL": "info"},
                         gateway["environment"])
        self.assertEqual(["versiond-pool"], services["versiond-0"]["networks"]["testenv"]["aliases"])
        self.assertNotIn("aliases", services["versiond-1"]["networks"]["testenv"])
        self.assertEqual("warn", services["versiond-1"]["environment"]["DEVSHARD_LOG_LEVEL"])
        self.assertEqual("60s", services["versiond-1"]["environment"]["VERSIOND_POLL_INTERVAL"])
        self.assertEqual({"GONKA_HA": "", "VERSIOND_ROUTING_ACTIVATION_MIN_READY": "1",
                          "VERSIOND_ROUTING_CATALOG_POLL_SECONDS": "15"}, services["versiond-router"]["environment"])
        self.assertEqual(["versiond-0"], services["versiond-router"]["depends_on"])
        dapi = services["mock-dapi"]["environment"]
        self.assertEqual(("v5", "file:///opt/devshard/devshardd", "0" * 64), (
            dapi["MOCK_DAPI_VERSION_NAME"], dapi["MOCK_DAPI_VERSION_BINARY"], dapi["MOCK_DAPI_VERSION_SHA256"]))

    def test_pinned_cpus_split_the_gateway_from_the_rest(self):
        services = testenv.patch_compose(compose_model(), "p", COMMIT, "0:0", "0", "1-7")["services"]
        self.assertEqual("0", services["devshardctl"]["cpuset"])
        self.assertEqual({"1-7"}, {service["cpuset"] for name, service in services.items() if name != "devshardctl"})

    def test_an_unknown_service_is_refused(self):
        model = compose_model()
        model["services"]["grafana"] = {"image": "grafana"}
        with self.assertRaisesRegex(testenv.TestenvError, "unknown service grafana"):
            testenv.patch_compose(model, "p", COMMIT, "0:0")

    def test_mock_openai_drops_the_alternative_bytes_inside_the_build(self):
        text = "FROM x AS build\nCOPY devshard/ .\nRUN go build ./testenv/cmd/mockopenai\n"
        patched = testenv.mock_openai_dockerfile(text)
        lines = patched.splitlines()
        self.assertEqual("COPY devshard/ .", lines[1])
        self.assertTrue(lines[2].startswith("RUN grep -q 'utf8CodeUnits(alt)'"))
        self.assertIn("sed -i", lines[2])
        self.assertEqual("RUN go build ./testenv/cmd/mockopenai", lines[3])
        with self.assertRaises(testenv.TestenvError):
            testenv.mock_openai_dockerfile("FROM x\n")

    def test_build_arguments_follow_the_machine(self):
        self.assertEqual(("amd64", "0"), testenv.arch_of("x86_64"))
        self.assertEqual(("arm64", "1"), testenv.arch_of("aarch64"))
        self.assertEqual(("arm64", "1"), testenv.arch_of("arm64"))
        with self.assertRaises(testenv.TestenvError):
            testenv.arch_of("riscv64")
        argv = testenv.build_argv("devshardd", "/src", COMMIT, "amd64", "0", "v5.0.2")
        self.assertEqual(["docker", "build", "--platform", "linux/amd64", "-t", testenv.image("devshardd", COMMIT),
                          "-f", "/src/devshard/Dockerfile", "--target", "runtime"], argv[:10])
        for item in ("BLST_PORTABLE=0", "GOARCH=amd64", "DEVSHARD_VERSION=v5", "DEVSHARD_BINARY_VERSION=v5.0.2",
                     "DEVSHARD_BUILD_TAGS="):
            self.assertIn(item, argv)
        self.assertEqual("/src", argv[-1])
        self.assertEqual("/src/versioned", testenv.build_argv("versiond", "/src", COMMIT, "arm64", "1", "v")[-1])
        argv = testenv.build_argv("mock-openai", "/src", COMMIT, "arm64", "1", "v", "/cache/Dockerfile.mo")
        self.assertEqual("/cache/Dockerfile.mo", argv[argv.index("-f") + 1])
        self.assertEqual("gcheck-tenv-mock-openai:%s" % COMMIT[:12], testenv.image("mock-openai", COMMIT))
        self.assertEqual("v5.0.2", testenv.binary_version(stress.TAG))


class Source(unittest.TestCase):
    def test_testenv_checkout_has_the_router_and_versiond_but_no_test_file(self):
        with tempfile.TemporaryDirectory() as tmp:
            upstream = os.path.join(tmp, "upstream")
            for folder in ("devshard/user", "common", "inference-chain", "versioned", "versiond-router",
                           "router-runtime", "proxy"):
                os.makedirs(os.path.join(upstream, folder))
                with open(os.path.join(upstream, folder, "README"), "w", encoding="utf-8") as handle:
                    handle.write(folder + "\n")
            run = {"cwd": upstream, "check": True, "capture_output": True}
            subprocess.run(["git", "init", "--quiet"], **run)
            subprocess.run(["git", "add", "."], **run)
            subprocess.run(["git", "-c", "user.email=t@example.invalid", "-c", "user.name=t", "commit", "--quiet",
                            "-m", "init"], **run)
            subprocess.run(["git", "tag", stress.TAG], **run)
            commit = subprocess.run(["git", "rev-parse", "HEAD"], text=True, **run).stdout.strip()
            cache = os.path.join(tmp, "cache")
            path, _ = stress.prepare_source(cache, repo="file://" + upstream, pinned=commit)
            self.assertTrue(os.path.isfile(os.path.join(path, stress.TEST_FILE)))
            self.assertFalse(os.path.exists(os.path.join(path, "versioned")))
            path, _ = stress.prepare_source(cache, repo="file://" + upstream, pinned=commit, sparse=testenv.SPARSE,
                                            test_file=False)
            for folder in ("versioned", "versiond-router", "router-runtime", "devshard"):
                self.assertTrue(os.path.isdir(os.path.join(path, folder)), folder)
            self.assertFalse(os.path.exists(os.path.join(path, "proxy")))
            self.assertFalse(os.path.exists(os.path.join(path, stress.TEST_FILE)))


class Parsing(unittest.TestCase):
    def test_host_diff_replies(self):
        reply = json.dumps([{"diff": {"nonce": 560}, "state_hash": "x"}, {"diff": {"nonce": "569"}},
                            {"diff": {}}, "noise"])
        self.assertEqual([560, 569], testenv.diff_nonces(reply))
        self.assertEqual([], testenv.diff_nonces("[]"))
        self.assertIsNone(testenv.diff_nonces('{"message":"no storage configured"}'))
        self.assertIsNone(testenv.diff_nonces("curl: (7) Failed to connect"))

    def test_host_last_reads_from_what_the_host_had(self):
        stored = list(range(0, 19870))
        calls = []

        def fetch(low, high):
            calls.append((low, high))
            return [nonce for nonce in stored if low <= nonce <= high]

        self.assertEqual(19869, testenv.host_last(fetch, 19900))
        self.assertEqual([(19400, 20400)], calls)
        calls.clear()
        self.assertEqual(19869, testenv.host_last(fetch, 21000, known=19869))
        self.assertEqual([(19869, 21500)], calls)

    def test_host_last_walks_back_when_the_host_is_far_behind(self):
        stored = list(range(0, 535))
        calls = []

        def fetch(low, high):
            calls.append((low, high))
            return [nonce for nonce in stored if low <= nonce <= high]

        self.assertEqual(534, testenv.host_last(fetch, 3000))
        self.assertEqual([(2500, 3500), (1500, 2500), (500, 1500)], calls)
        self.assertIsNone(testenv.host_last(lambda low, high: [], 100))
        self.assertEqual(7, testenv.host_last(lambda low, high: None, 100, known=7))

    def test_status_nonce_from_the_gateway(self):
        with Fake(cap=0) as fake:
            fake.nonce = 19800
            self.assertEqual(19800, stand.nonce_of(fake.base))
        self.assertIsNone(stand.nonce_of("http://127.0.0.1:1"))

    def test_cadence_counters_and_log_lines(self):
        text = ('devshard_gateway_heightsync_cadence_events_total{devshard_id="1",event="heartbeat_opened"} 7\n'
                'devshard_gateway_heightsync_cadence_events_total{devshard_id="2",event="heartbeat_opened"} 3\n'
                'devshard_gateway_heightsync_cadence_events_total{devshard_id="1",event="turn_abandoned"} 1\n'
                'devshard_gateway_heightsync_turns_abandoned_total{devshard_id="1"} 1\n')
        self.assertEqual({"heartbeat_opened": 10, "turn_abandoned": 1}, testenv.cadence(text))
        log = ("WARN heartbeat host dead subsystem=heightsync nonce=570 error=\"status 500: nonce 570 exceeds active "
               "cap 535\"\nWARN heartbeat host dead error=\"context deadline exceeded\"\nINFO heartbeat span\n")
        self.assertEqual((1, 2), testenv.count_lines(log))

    def test_docker_stats_of_gateway_and_hosts(self):
        text = ("p-devshardctl\t12.50%\t117MiB / 7.6GiB\t1.2MB / 3.4kB\t0B / 4.1MB\n"
                "p-versiond-0\t--\t0B / 0B\t0B / 0B\t0B / 0B\nbroken line\n")
        stats = testenv.parse_stats(text)
        self.assertEqual({"cpu_pct": 12.5, "mem_mb": 117.0, "rx_mb": 1.2, "tx_mb": 0.0034, "read_mb": 0.0,
                          "write_mb": 4.1}, stats["p-devshardctl"])
        self.assertIsNone(stats["p-versiond-0"]["cpu_pct"])
        self.assertEqual(2, len(stats))

    def test_docker_log_window_is_in_nanoseconds(self):
        self.assertEqual("1700000000.250000000", testenv._stamp(1700000000.25))


class Rates(unittest.TestCase):
    def test_quiet_nonces_per_minute_and_per_turn(self):
        samples = [sample("quiet", 100, 32, heartbeats=7), sample("quiet", 160, 52, heartbeats=8),
                   sample("quiet", 295, 100, heartbeats=14, cap=3)]
        rates = testenv.quiet_rates(samples)
        self.assertEqual({"samples": 3, "minutes": 3.2, "nonces": 68, "per_min": 20.9, "turns": 7, "per_turn": 9.7,
                          "turn_s": 27.9, "abandoned": 0, "cap_lines": 3, "dead_lines": 3}, rates)
        self.assertEqual({"samples": 1}, testenv.quiet_rates(samples[:1]))
        self.assertIsNone(testenv.quiet_rates([sample("quiet", 0, 5), sample("quiet", 10, 5)])["per_turn"])

    def test_summary_rates_hosts_and_the_active_cap(self):
        item = summary()
        self.assertEqual(9.4, item["nonces_per_s"])
        self.assertEqual(19800, item["drive_nonce"])
        self.assertTrue(item["reached"])
        self.assertEqual(20450, item["nonce"])
        self.assertEqual((19869, 19869), (item["host_last_min"], item["host_last_max"]))
        self.assertEqual(19935, item["active_cap"])
        self.assertEqual(130.0, item["quiet"]["per_min"])
        self.assertEqual({"host": 3, "slots": 16, "cpu_mean_pct": 13.0, "mem_peak_mb": 103.0, "last_diff": 19869},
                         item["per_host"][3])
        self.assertEqual(40, item["cap_lines"])


class Verdict(unittest.TestCase):
    def verdict(self, item):
        result = testenv.judge(item)
        return result["verdict"], result["reason"]

    def test_a_settled_escrow_after_the_cap_passes(self):
        value, reason = self.verdict(summary())
        self.assertEqual("PASS", value)
        self.assertIn("weight 64 of 43", reason)

    def test_a_failed_finalize_after_the_cap_fails_with_the_evidence(self):
        final = {"code": 500, "seconds": 25.4, "weight": 0, "quorum": 43, "signatures": 0,
                 "error": "insufficient signatures: 0/43 weight"}
        value, reason = self.verdict(summary(final=final))
        self.assertEqual("FAIL", value)
        for part in ("finalize answered 500 insufficient signatures: 0/43 weight", "gateway nonce 20450",
                     "hosts' last diff 19869..19869", "active cap 19935", "40 refusals"):
            self.assertIn(part, reason)
        final["code"], final["weight"], final["error"] = 200, 40, None
        self.assertEqual("FAIL", self.verdict(summary(final=final))[0])

    def test_a_drive_that_never_reached_the_routing_stop_is_inconclusive(self):
        samples = [sample("drive", 0, 0), sample("drive", 600, 5200)]
        value, reason = self.verdict(summary(samples=samples, drive_reason="no nonce progress for 600 s"))
        self.assertEqual("INCONCLUSIVE", value)
        self.assertEqual("drive stopped at nonce 5200 of 19800: no nonce progress for 600 s", reason)

    def test_setup_errors_block_and_interrupts_are_inconclusive(self):
        self.assertEqual(("BLOCKED", "gencompose failed"),
                         self.verdict(testenv.summarize(64, 4, 8, "drive", None, None, [], None,
                                                        error="gencompose failed")))
        self.assertEqual("INCONCLUSIVE", self.verdict(summary(stop="interrupted"))[0])

    def test_a_stopped_gateway_fails_and_a_stopped_host_is_inconclusive(self):
        value, reason = self.verdict(summary(stopped=["gcheck-tenv-ab12-g64-devshardctl exited 137 (out of memory)"]))
        self.assertEqual("FAIL", value)
        self.assertIn("out of memory", reason)
        self.assertEqual("INCONCLUSIVE", self.verdict(summary(stopped=["gcheck-tenv-ab12-g64-versiond-2 exited 1"]))[0])

    def test_quiet_only_is_informational(self):
        samples = [sample("warm", 0, 30), sample("quiet", 10, 30, heartbeats=1),
                   sample("quiet", 130, 300, heartbeats=5), sample("final", 140, 365, heartbeats=5)]
        value, reason = self.verdict(summary(mode="quiet-only", samples=samples))
        self.assertEqual("PASS", value)
        self.assertIn("quiet 135.0 nonces/min, 67.5 per turn over 4 turns (G+1 = 65), 0 abandoned", reason)
        self.assertEqual("INCONCLUSIVE", self.verdict(summary(mode="quiet-only", samples=samples[:2]))[0])

    def test_dry_run_needs_chats_finalize_and_host_diffs(self):
        samples = [sample("warm", 0, 4), sample("final", 9, 13, last=4)]
        final = {"code": 200, "seconds": 5.9, "weight": 8, "quorum": 6}
        self.assertEqual("PASS", self.verdict(summary(mode="dry-run", samples=samples, final=final))[0])
        value, reason = self.verdict(summary(mode="dry-run", samples=samples[:1], final=final))
        self.assertEqual(("FAIL", "no host diffs readable through the router"), (value, reason))


class Driving(unittest.TestCase):
    def test_the_drive_stops_where_the_gateway_stops_routing(self):
        with Fake(cap=30, per_request=2) as fake:
            drive = testenv.Drive(fake.base, 4, testenv.ROUTING_STOP, "t")
            drive.run(every_s=0.05, max_s=20)
        self.assertEqual(testenv.ROUTED_STOP, drive.reason)
        self.assertTrue(testenv.reached(drive, []))

    def test_quarantined_hosts_are_cleared_and_the_drive_goes_on(self):
        with Fake(cap=12, quarantined=1) as fake:
            drive = testenv.Drive(fake.base, 2, testenv.ROUTING_STOP, "t", ["gonka1aaa", "gonka1bbb"])
            drive.run(every_s=0.05, max_s=20)
        self.assertEqual(testenv.ROUTED_STOP, drive.reason)
        self.assertEqual(1, drive.unquarantines)
        self.assertEqual(2, len(fake.unquarantined))
        self.assertGreaterEqual(drive.codes.get(503, 0), 1)

    def test_warm_up_needs_one_answer(self):
        with Fake(status=500) as fake:
            with self.assertRaisesRegex(testenv.TestenvError, "warm-up: no chat answered 200 of 3"):
                testenv.warm_up(fake.base, 3, "t")
        with Fake(cap=100) as fake:
            self.assertEqual({200: 3}, testenv.warm_up(fake.base, 3, "t").codes)

    def test_quiet_ends_on_time_or_on_a_guard(self):
        taken = []
        self.assertIsNone(testenv.quiet(lambda: taken.append(1), 0.001, 0.01))
        self.assertGreaterEqual(len(taken), 2)
        self.assertEqual("disk below 5% free at /", testenv.quiet(lambda: None, 1, 0.01,
                                                                 lambda: "disk below 5% free at /"))

    def test_finalize_counts_signature_weight_by_slot(self):
        with Fake(cap=100, groups=8) as fake, tempfile.TemporaryDirectory() as tmp:
            final = testenv.finalize(fake.base, 8, os.path.join(tmp, "finalize.json"))
            with open(os.path.join(tmp, "finalize.json"), encoding="utf-8") as handle:
                saved = json.load(handle)
        self.assertEqual((200, 10, 8, 6), (final["code"], final["signatures"], final["weight"], final["quorum"]))
        self.assertEqual(8, len(saved["reply"]["host_stats"]))
        self.assertEqual(200, saved["code"])
        with Fake(cap=100, groups=64, quorum_reached=False) as fake:
            final = testenv.finalize(fake.base, 64)
        self.assertEqual((500, "insufficient signatures: 0/43 weight", 0), (final["code"], final["error"],
                                                                            final["weight"]))


class Cleanup(unittest.TestCase):
    def test_only_resources_of_this_mode_go(self):
        listings = {
            "ps": "gcheck-tenv-ab12-g64-devshardctl\tgcheck-tenv-ab12-g64\nother-db-1\tother\n"
                  "gcheck-gw-ab12-g8-h3-c8-gateway\t\ntenv-g8n3-versiond-0-1\ttenv-g8n3\n"
                  "gcheck-tenv-ab12-g64-gencompose\t\n",
            "network": "bridge\t\ngcheck-tenv-ab12-g64_testenv\tgcheck-tenv-ab12-g64\nkind\t\n",
            "volume": "gcheck-tenv-ab12-g64_versiond-router-state\tgcheck-tenv-ab12-g64\npgdata\tother\n",
            "images": "gcheck-tenv-devshardd:eddae498572a\ngcheck-gw-gateway:eddae498572a\n"
                      "tenv-devshardd:v5.0.2\n<none>:<none>\npostgres:16-alpine\n"}
        calls = []

        def run(args, check=True, timeout=None):
            calls.append(args)
            return mock.Mock(returncode=0, stdout=listings[args[0]] if "--format" in args else "")

        with tempfile.TemporaryDirectory() as tmp:
            work = os.path.join(tmp, "testenv")
            os.makedirs(os.path.join(work, "gcheck-tenv-ab12-g64", "data"))
            removed = testenv.cleanup([work, os.path.join(tmp, "absent")], run)
            self.assertFalse(os.path.exists(work))
        self.assertEqual(["gcheck-tenv-ab12-g64-devshardctl", "gcheck-tenv-ab12-g64-gencompose"],
                         removed["containers"])
        self.assertEqual(["gcheck-tenv-ab12-g64_testenv"], removed["networks"])
        self.assertEqual(["gcheck-tenv-ab12-g64_versiond-router-state"], removed["volumes"])
        self.assertEqual(["gcheck-tenv-devshardd:eddae498572a"], removed["images"])
        self.assertEqual([work], removed["dirs"])
        mutations = [args for args in calls if "--format" not in args]
        self.assertEqual([["rm", "-f", "gcheck-tenv-ab12-g64-devshardctl", "gcheck-tenv-ab12-g64-gencompose"],
                          ["network", "rm", "gcheck-tenv-ab12-g64_testenv"],
                          ["volume", "rm", "gcheck-tenv-ab12-g64_versiond-router-state"],
                          ["rmi", "gcheck-tenv-devshardd:eddae498572a"]], mutations)
        self.assertFalse(any("prune" in args for args in calls))

    def test_root_owned_files_go_through_a_container(self):
        calls = []
        with tempfile.TemporaryDirectory() as tmp:
            path = os.path.join(tmp, "stack")
            os.makedirs(path)
            with mock.patch.object(testenv.shutil, "rmtree", side_effect=[PermissionError("root"), None]):
                testenv.remove_tree(path, lambda args, **kw: calls.append(args))
        self.assertEqual(["run", "--rm"], calls[0][:2])
        self.assertIn("%s:/w" % tmp, calls[0])
        self.assertEqual(["rm", stress.GO_IMAGE, "-rf", "/w/stack"], calls[0][-4:])


class Cli(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.env = {name: os.environ.get(name) for name in ("XDG_CONFIG_HOME", "XDG_DATA_HOME")}
        os.environ["XDG_CONFIG_HOME"] = os.path.join(self.tmp.name, "config")
        os.environ["XDG_DATA_HOME"] = os.path.join(self.tmp.name, "data")

    def tearDown(self):
        for name, value in self.env.items():
            if value is None:
                os.environ.pop(name, None)
            else:
                os.environ[name] = value

    def gcheck(self, *args):
        out, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            code = cli.main(list(args))
        self.out, self.err = out.getvalue(), err.getvalue()
        return code

    @contextlib.contextmanager
    def docker_free(self, fake, last=lambda i, low, high: [low]):
        self.generated, self.downs = [], []

        def generate(stack, source, cache, devshardd, commit, version, log_path, octet=77, gateway_cpus=None,
                     host_cpus=None):
            self.generated.append((stack.groups, stack.hosts, octet, gateway_cpus, host_cpus))
            stack.services = ["devshardctl", "versiond-0", "versiond-router"]
            stack.addresses = ["gonka1aaa"]

        with mock.patch.object(stress.shutil, "which", return_value="/usr/bin/docker"), \
                mock.patch.object(stress, "prepare_source", return_value=("/src/gonka", COMMIT)) as source, \
                mock.patch.object(testenv, "build_images", return_value=("/cache/devshardd", [])), \
                mock.patch.object(testenv.Stack, "generate", generate), \
                mock.patch.object(testenv.Stack, "up", lambda stack: fake.base), \
                mock.patch.object(testenv.Stack, "down", lambda stack: self.downs.append(stack.project)), \
                mock.patch.object(testenv.Stack, "exited", lambda stack: []), \
                mock.patch.object(testenv.Stack, "logs", lambda stack, service, tail=2000: "line\n"), \
                mock.patch.object(testenv.Stack, "stats", lambda stack: {}), \
                mock.patch.object(testenv.Stack, "gateway_log", lambda stack, since, until: ""), \
                mock.patch.object(testenv.Stack, "diffs", lambda stack, i, low, high: last(i, low, high)), \
                mock.patch.object(stand, "memory_guard", return_value=None), \
                mock.patch.object(stand, "docker_root", return_value=None):
            yield source

    def run_dir(self):
        return self.out.split("written  ")[1].split(":")[0]

    def test_help_and_bad_options(self):
        with contextlib.redirect_stdout(io.StringIO()) as out, self.assertRaises(SystemExit):
            cli.main(["gateway-load", "testenv", "--help"])
        self.assertIn("--quiet-only", out.getvalue())
        self.assertEqual(4, self.gcheck("gateway-load", "testenv", "--groups", "0"))
        self.assertEqual(4, self.gcheck("gateway-load", "testenv", "--hosts", "65"))
        self.assertEqual(4, self.gcheck("gateway-load", "testenv", "--quiet-minutes", "0"))
        self.assertEqual(4, self.gcheck("gateway-load", "testenv", "--gateway-cpus", "0-"))
        with contextlib.redirect_stderr(io.StringIO()), self.assertRaises(SystemExit):
            cli.main(["gateway-load", "testenv", "--concurrency", "0"])

    def test_plan_names_the_testenv_mode(self):
        with mock.patch.object(stress, "pick_runner", side_effect=stress.StressError("needs docker")):
            self.assertEqual(0, self.gcheck("gateway-load", "plan"))
        self.assertIn("testenv  real devshardd hosts", self.out)
        self.assertIn("gcheck-tenv-<image>:<commit>", self.out)
        self.assertIn("testenv: report.md, samples.csv, hosts.csv", self.out)

    def test_dry_run_brings_up_g8_on_three_hosts(self):
        with Fake(cap=100, groups=8) as fake, self.docker_free(fake) as source:
            code = self.gcheck("gateway-load", "testenv", "--dry-run", "--groups", "64")
        self.assertEqual(0, code, self.out + self.err)
        self.assertIn("ready    READY", self.out)
        self.assertEqual([(8, 3, 77, None, None)], self.generated)
        self.assertEqual(3, fake.chats)
        self.assertEqual(1, len(self.downs))
        self.assertEqual(testenv.SPARSE, source.call_args[1]["sparse"])
        self.assertFalse(source.call_args[1]["test_file"])

    def test_dry_run_without_host_diffs_is_blocked(self):
        with Fake(cap=100, groups=8) as fake, self.docker_free(fake, last=lambda i, low, high: None):
            code = self.gcheck("gateway-load", "testenv", "--dry-run")
        self.assertEqual(3, code, self.out + self.err)
        self.assertIn("ready    BLOCKED\n         no host diffs readable through the router", self.out)

    def test_quiet_only_samples_every_group_size(self):
        with Fake(groups=16) as fake, self.docker_free(fake):
            code = self.gcheck("gateway-load", "testenv", "--groups", "16,8", "--hosts", "4", "--quiet-only",
                               "--quiet-minutes", "0.005", "--every", "0.05", "--gateway-cpus", "0",
                               "--host-cpus", "1-7")
        self.assertEqual(0, code, self.out + self.err)
        self.assertEqual([(8, 4, 77, "0", "1-7"), (16, 4, 78, "0", "1-7")], self.generated)
        self.assertIn("PASS         testenv_g8", self.out)
        self.assertIn("PASS         testenv_g16", self.out)
        self.assertEqual(2, len(self.downs))
        for name in ("report.md", "samples.csv", "hosts.csv", "summary.json", "manifest.json", "g8/finalize.json",
                     "g16/gateway.log", "g16/host-0.log"):
            self.assertTrue(os.path.isfile(os.path.join(self.run_dir(), name)), name)
        with open(os.path.join(self.run_dir(), "report.md"), encoding="utf-8") as handle:
            text = handle.read()
        self.assertIn("| testenv_g16 | PASS |", text)
        self.assertIn("CPUs: gateway 0, hosts, router and mocks 1-7.", text)
        with open(os.path.join(self.run_dir(), "hosts.csv"), encoding="utf-8") as handle:
            self.assertEqual(",".join(report.HOST_FIELDS), handle.readline().strip())

    def test_drive_to_the_routing_stop_then_quiet_and_a_failed_finalize(self):
        with Fake(cap=40, groups=64, quorum_reached=False) as fake, \
                self.docker_free(fake, last=lambda i, low, high: [min(high, 35)]):
            code = self.gcheck("gateway-load", "testenv", "--concurrency", "4", "--quiet-minutes", "0.002",
                               "--every", "0.05", "--keep")
        self.assertEqual(1, code, self.out + self.err)
        self.assertIn("FAIL         testenv_g64   finalize answered 500 insufficient signatures: 0/43 weight", self.out)
        self.assertIn("hosts' last diff 35..35, active cap 19935", self.out)
        self.assertEqual([], self.downs)
        with open(os.path.join(self.run_dir(), "summary.json"), encoding="utf-8") as handle:
            data = json.load(handle)
        self.assertTrue(data["summaries"][0]["reached"])
        self.assertEqual(4, data["summaries"][0]["hosts"])
        with open(os.path.join(self.run_dir(), "samples.csv"), encoding="utf-8") as handle:
            phases = {line.split(",")[1] for line in handle.read().splitlines()[1:]}
        self.assertLessEqual({"up", "warm", "quiet", "settle", "final"}, phases)

    def test_a_stack_that_cannot_start_blocks_the_run(self):
        def broken(stack, *args, **kw):
            raise testenv.TestenvError("gencompose failed, see gencompose.log")

        with Fake() as fake, self.docker_free(fake), mock.patch.object(testenv.Stack, "generate", broken):
            code = self.gcheck("gateway-load", "testenv", "--groups", "32,64")
        self.assertEqual(3, code, self.out + self.err)
        self.assertIn("BLOCKED      testenv_g32   gencompose failed", self.out)
        self.assertNotIn("testenv_g64", self.out)

    def test_cleanup_takes_the_lock_and_lists_what_went(self):
        removed = {"containers": ["gcheck-tenv-ab12-g64-devshardctl"], "networks": [], "volumes": [], "dirs": [],
                   "images": ["gcheck-tenv-devshardd:eddae498572a"]}
        with mock.patch.object(stress.shutil, "which", return_value="/usr/bin/docker"), \
                mock.patch.object(testenv, "cleanup", return_value=removed) as cleanup:
            self.assertEqual(0, self.gcheck("gateway-load", "testenv", "--cleanup"))
        roots = cleanup.call_args[0][0]
        self.assertTrue(roots[0].endswith(os.path.join("gonka-check", "testenv")))
        self.assertTrue(roots[1].endswith(os.path.join("cache", "gateway-load", "testenv")))
        self.assertIn("removed  containers: gcheck-tenv-ab12-g64-devshardctl", self.out)
        self.assertIn("removed  networks: none", self.out)
        self.assertIn("removed  images: gcheck-tenv-devshardd:eddae498572a", self.out)


if __name__ == "__main__":
    unittest.main()
