import assert from 'node:assert/strict';
import {replaySlots,consistentQuery,causalEvidence,missingApprovalEvidence} from './causal.mjs';
const addresses={node0:'gonka1k86rjz744dmdz56cpnrjxwa4a3esu8js65uu60',node1:'gonka1caueq4z7pfq8lltnj9v3fcwf4s05sxqyusrylx',node3:'gonka19fx3gsnx24wy99aagvtjepqw65kznp6y386elc',node4:'gonka1the2335jnlfe6lvxyqt9c6zahpdxfuk4xp8pz2','node5-2':'gonka17dlt8p0ystz54s2p50wllzfg8kjq9afresjd67'};
const powers={node0:94,node1:27,node3:94,node4:122,'node5-2':70};
const model='Qwen/Qwen3-0.6B';
const snapshot={app_hash:'997932ee82eab9d9a20636b04b2f82305380da4b19f285073595dc185f30f10f',total_network_weight:'407',model_voting_powers:[{model_id:model,voting_powers:Object.keys(addresses).map(n=>({address:addresses[n],voting_power:String(powers[n])}))}]};
for(const [participant,expected]of [['node0',['node3','node4']],['node3',['node3','node1']],['node4',['node5-2','node4']]])assert.deepEqual(await replaySlots(snapshot,addresses[participant],model,2),expected.map(n=>addresses[n]));
const reverse=structuredClone(snapshot);reverse.model_voting_powers[0].voting_powers.reverse();assert.deepEqual(await replaySlots(reverse,addresses.node3,model,2),await replaySlots(snapshot,addresses.node3,model,2));
const duplicate={app_hash:'x',total_network_weight:'1',model_voting_powers:[{model_id:model,voting_powers:[{address:'a',voting_power:'1'}]}]};assert.deepEqual(await replaySlots(duplicate,'p',model,2),['a','a'],'duplicate slots count separately');
duplicate.total_network_weight='3';assert.deepEqual(await replaySlots(duplicate,'p',model,2),[],'round down unsampled network share');
await assert.rejects(replaySlots(snapshot,'a',model,1001));
assert.equal(consistentQuery({queries:[]},1,'x'),null);
assert.equal(consistentQuery({queries:[{height:1,path:'x',status:'reported',pages:[{x:1}]},{height:1,path:'x',status:'reported',pages:[{x:2}]}]},1,'x'),null);
assert.equal(await causalEvidence({},null,{}),null);
console.log('PASS: exact incident slot vectors, stable order, duplicate slots, abstention rounding, conflicts and missing evidence');
const peer={label:'node1',address:'a'},rows=[{address:'a',decisions:[{kind:'participant.preserved'}]}];
const report={decision_logs:[{node:'node1',height:44,kind:'poc.worker_filter',fields:{numNodes:'0'}},{node:'node3',height:44,kind:'poc.worker_filter',fields:{numNodes:'1'}}]};
let why=missingApprovalEvidence(report,peer,rows,44,48);assert.equal(why.status,'zero_workers');assert.equal(why.logs.length,1);assert.equal(why.preserved.length,1);
assert.equal(missingApprovalEvidence(report,peer,rows,45,48).status,'unexplained');
report.decision_logs.push({node:'node1',height:46,kind:'poc.worker_filter',fields:{numNodes:'1'}});
assert.equal(missingApprovalEvidence(report,peer,rows,44,48).status,'mixed_workers');
why=missingApprovalEvidence({log_sources:[{node:'node5',component:'api',process:{created:'2026-09-09T19:23:02Z'},window_end:'2026-09-09T18:59:33Z'}]}, {label:'node5-2',address:'b'},[],44,48);
assert.equal(why.status,'unexplained');assert.ok(why.laterContainer);assert.equal(why.identityBound,false);
assert.equal(missingApprovalEvidence({},peer,[],44,48).status,'unexplained');
console.log('PASS: missing approval reasons are peer/window scoped; zero and mixed workers differ; preserved is separate; later host container is not historical peer proof');
